```{r negative_bin_function}

negative_bin <- function(data){
  
  age <- c(18, 24, 30, 36, 42, 48, 54, 60, 66, 72)
  freq_list <- rep(0, 10)
  n_speaker_list <- rep(0, 10)
  n_utterances_list <- rep(0, 10)

  for (i in 1:length(age)){
    age_min = 0
    age_max = age[i]
    if (i == 1){
      age_min = 12
    }
    else{
      age_min = age[i - 1]
    }
  
    freq = 0
    n_speaker = 0
    n_utterances = 0
  
    for (z in 1:nrow(data)){

      if (as.numeric(as.vector(data$Age)[z]) < age_max & as.numeric(as.vector(data$Age)[z]) >= age_min){
        freq = freq + as.numeric(as.vector(data$Freq)[z])
        n_speaker = n_speaker + as.numeric(as.vector(data$N_speaker)[z])
        n_utterances = n_utterances + as.numeric(as.vector(data$N_utterance)[z])
      }
    }
    freq_list[i] = freq
    n_speaker_list[i] = n_speaker
    n_utterances_list[i] = n_utterances
    
    }

  moving_ave <- data.frame(as.character(age))
  names(moving_ave) <- c('Age')
  moving_ave$Freq <- freq_list
  moving_ave$Role <- rep(unique(data$Role), length(age))
  moving_ave$Head <- rep(unique(data$Head), length(age))
  moving_ave$N_speaker <- n_speaker_list
  moving_ave$N_utterance <- n_utterances_list
  moving_ave$Total_ratio <- moving_ave$Freq / moving_ave$N_utterance
  moving_ave$Ratio <- rep(0, length(age))
  moving_ave$Polarity <- rep(unique(data$Polarity), length(age))
  moving_ave$Measure <- rep('negative construction moving ratio', length(age))
  moving_ave$Which <- rep('moving ratio', length(age))
  temp <- rbind(data, moving_ave)
  data <- temp
  
  return(data)

}

```

```{r positive_bin_function}

positive_bin <- function(data){
  
  age <- c(18, 24, 30, 36, 42, 48, 54, 60, 66, 72)
  freq_list <- rep(0, 10)
  n_speaker_list <- rep(0, 10)
  n_utterances_list <- rep(0, 10)

  for (i in 1:length(age)){
    age_min = 0
    age_max = age[i]
    if (i == 1){
      age_min = 12
    }
    else{
      age_min = age[i - 1]
    }
  
    freq = 0
    n_speaker = 0
    n_utterances = 0
  
    for (z in 1:nrow(data)){

      if (as.numeric(as.vector(data$Age)[z]) < age_max & as.numeric(as.vector(data$Age)[z]) >= age_min){
        freq = freq + as.numeric(as.vector(data$Freq)[z])
        n_speaker = n_speaker + as.numeric(as.vector(data$N_speaker)[z])
        n_utterances = n_utterances + as.numeric(as.vector(data$N_utterance)[z])
      }
    }
    freq_list[i] = freq
    n_speaker_list[i] = n_speaker
    n_utterances_list[i] = n_utterances
    
    }

  moving_ave <- data.frame(as.character(age))
  names(moving_ave) <- c('Age')
  moving_ave$Freq <- freq_list
  moving_ave$Role <- rep(unique(data$Role), length(age))
  moving_ave$Head <- rep(unique(data$Head), length(age))
  moving_ave$N_speaker <- n_speaker_list
  moving_ave$N_utterance <- n_utterances_list
  moving_ave$Total_ratio <- moving_ave$Freq / moving_ave$N_utterance
  moving_ave$Ratio <- rep(0, length(age))
  moving_ave$Polarity <- rep(unique(data$Polarity), length(age))
  moving_ave$Measure <- rep('positive construction moving ratio', length(age))
  moving_ave$Which <- rep('moving ratio', length(age))
  temp <- rbind(data, moving_ave)
  data <- temp
  
  return(data)

}

```


```{r individualemotiondata, include=FALSE}

emotion_children = ''

children <- as.vector(unique(subset(emotion, Age<=36)$Child))

for (i in 1:length(children)){
  select <- data.frame(subset(emotion, Child == children[i] & Polarity == 'negative' & Role == 'Child' & grepl(' nan', children[i]) == FALSE))
    if (min(as.vector(unique(select$Age))) < 24 & as.numeric(length(unique(select$Age))) >= 8){
  emotion_children = c(children[i], emotion_children)
  }
}

emotion_children = emotion_children[1: length(emotion_children) - 1]

individual_emotion_data = 0

for (i in emotion_children){
  child_individual_like_neg <- subset(child_emotion_neg, Head %in% c('like') & Child == i)
  child_individual_want_neg <- subset(child_emotion_neg, Head %in% c('want') & Child == i)
  parent_individual_like_neg <- subset(parent_emotion_neg, Head %in% c('like') & Child == i)
  parent_individual_want_neg <- subset(parent_emotion_neg, Head %in% c('want') & Child == i)
  
  child_individual_like_pos <- subset(child_emotion_pos, Head %in% c('like') & Child == i)
  child_individual_want_pos <- subset(child_emotion_pos, Head %in% c('want') & Child == i)
  parent_individual_like_pos <- subset(parent_emotion_pos, Head %in% c('like') & Child == i)
  parent_individual_want_pos <- subset(parent_emotion_pos, Head %in% c('want') & Child == i)
  
  child_individual_like_neg <- data.frame(table(child_individual_like_neg$Age))
  
  if (nrow(child_individual_like_neg) != 0){
  names(child_individual_like_neg) <- c('Age', 'Freq')
  child_individual_like_neg$Role <- rep('Child', nrow(child_individual_like_neg))
  child_individual_like_neg$Head <- rep('like', nrow(child_individual_like_neg))
  temp <- merge(child_individual_like_neg, subset(child_individual_descriptive, Child == i)[, -c(4)], by.x = 'Age', all.x = TRUE)
  child_individual_like_neg <- temp
  child_individual_like_neg$Total_ratio <- child_individual_like_neg$Freq /    child_individual_like_neg$N_utterance
child_individual_like_neg$Ratio <- child_individual_like_neg$Freq / sum(child_individual_like_neg$Freq)
child_individual_like_neg$Polarity <- rep('negative', nrow(child_individual_like_neg))
child_individual_like_neg$Measure <- rep('negative construction ratio', nrow(child_individual_like_neg))
child_individual_like_neg$Which <- rep('ratio', nrow(child_individual_like_neg))
child_individual_like_neg$Function <- rep('Rejection', nrow(child_individual_like_neg))
child_individual_like_neg <- negative_moving(child_individual_like_neg, subset(child_individual_descriptive, Child == i))
child_individual_like_neg$Child <- rep(i, nrow(child_individual_like_neg))
individual_emotion_data <- rbind(child_individual_like_neg, individual_emotion_data)
}
child_individual_want_neg <- data.frame(table(child_individual_want_neg$Age))
  if (nrow(child_individual_want_neg) != 0){
names(child_individual_want_neg) <- c('Age', 'Freq')
child_individual_want_neg$Role <- rep('Child', nrow(child_individual_want_neg))
child_individual_want_neg$Head <- rep('want', nrow(child_individual_want_neg))
temp <- merge(child_individual_want_neg, subset(child_individual_descriptive, Child == i)[, -c(4)], by.x = 'Age', all.x = TRUE)
child_individual_want_neg <- temp
child_individual_want_neg$Total_ratio <- child_individual_want_neg$Freq / child_individual_want_neg$N_utterance
child_individual_want_neg$Ratio <- child_individual_want_neg$Freq / sum(child_individual_want_neg$Freq)
child_individual_want_neg$Polarity <- rep('negative', nrow(child_individual_want_neg))
child_individual_want_neg$Measure <- rep('negative construction ratio', nrow(child_individual_want_neg))
child_individual_want_neg$Which <- rep('ratio', nrow(child_individual_want_neg))
child_individual_want_neg$Function <- rep('Rejection', nrow(child_individual_want_neg))
child_individual_want_neg <- negative_moving(child_individual_want_neg, subset(child_individual_descriptive, Child == i))
child_individual_want_neg$Child <- rep(i, nrow(child_individual_want_neg))
individual_emotion_data <- rbind(child_individual_want_neg, individual_emotion_data)
  }
  
parent_individual_like_neg <- data.frame(table(parent_individual_like_neg$Age))
  if (nrow(parent_individual_like_neg) != 0){
names(parent_individual_like_neg) <- c('Age', 'Freq')
parent_individual_like_neg$Role <- rep('Parent', nrow(parent_individual_like_neg))
parent_individual_like_neg$Head <- rep('like', nrow(parent_individual_like_neg))
temp <- merge(parent_individual_like_neg, subset(parent_individual_descriptive, Child == i)[, -c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_like_neg <- temp
parent_individual_like_neg$Total_ratio <- parent_individual_like_neg$Freq / parent_individual_like_neg$N_utterance
parent_individual_like_neg$Ratio <- parent_individual_like_neg$Freq / sum(parent_individual_like_neg$Freq)
parent_individual_like_neg$Polarity <- rep('negative', nrow(parent_individual_like_neg))
parent_individual_like_neg$Measure <- rep('negative construction ratio', nrow(parent_individual_like_neg))
parent_individual_like_neg$Which <- rep('ratio', nrow(parent_individual_like_neg))
parent_individual_like_neg$Function <- rep('Rejection', nrow(parent_individual_like_neg))
parent_individual_like_neg <- negative_moving(parent_individual_like_neg, subset(parent_individual_descriptive, Child == i))
parent_individual_like_neg$Child <- rep(i, nrow(parent_individual_like_neg))
individual_emotion_data <- rbind(parent_individual_like_neg, individual_emotion_data)
  }
  
parent_individual_want_neg <- data.frame(table(parent_individual_want_neg$Age))
if (nrow(parent_individual_want_neg) != 0){
names(parent_individual_want_neg) <- c('Age', 'Freq')
parent_individual_want_neg$Role <- rep('Parent', nrow(parent_individual_want_neg))
parent_individual_want_neg$Head <- rep('want', nrow(parent_individual_want_neg))
temp <- merge(parent_individual_want_neg, subset(parent_individual_descriptive, Child == i)[, -c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_want_neg <- temp
parent_individual_want_neg$Total_ratio <- parent_individual_want_neg$Freq / parent_individual_want_neg$N_utterance
parent_individual_want_neg$Ratio <- parent_individual_want_neg$Freq / sum(parent_individual_want_neg$Freq)
parent_individual_want_neg$Polarity <- rep('negative', nrow(parent_individual_want_neg))
parent_individual_want_neg$Measure <- rep('negative construction ratio', nrow(parent_individual_want_neg))
parent_individual_want_neg$Which <- rep('ratio', nrow(parent_individual_want_neg))
parent_individual_want_neg$Function <- rep('Rejection', nrow(parent_individual_want_neg))
parent_individual_want_neg <- negative_moving(parent_individual_want_neg, subset(parent_individual_descriptive, Child == i))
parent_individual_want_neg$Child <- rep(i, nrow(parent_individual_want_neg))
individual_emotion_data <- rbind(parent_individual_want_neg, individual_emotion_data)
}
  
child_individual_like_pos <- data.frame(table(child_individual_like_pos$Age))
if (nrow(child_individual_like_pos) != 0){
names(child_individual_like_pos) <- c('Age', 'Freq')
child_individual_like_pos$Role <- rep('Child', nrow(child_individual_like_pos))
child_individual_like_pos$Head <- rep('like', nrow(child_individual_like_pos))
temp <- merge(child_individual_like_pos, subset(child_individual_descriptive, Child == i)[, -c(4)], by.x = 'Age', all.x = TRUE)
child_individual_like_pos <- temp
child_individual_like_pos$Total_ratio <- child_individual_like_pos$Freq / child_individual_like_pos$N_utterance
child_individual_like_pos$Ratio <- child_individual_like_pos$Freq / sum(child_individual_like_pos$Freq)
child_individual_like_pos$Polarity <- rep('positive', nrow(child_individual_like_pos))
child_individual_like_pos$Measure <- rep('positive construction ratio', nrow(child_individual_like_pos))
child_individual_like_pos$Which <- rep('ratio', nrow(child_individual_like_pos))
child_individual_like_pos$Function <- rep('Rejection', nrow(child_individual_like_pos))
child_individual_like_pos <- positive_moving(child_individual_like_pos, subset(child_individual_descriptive, Child == i))
child_individual_like_pos$Child <- rep(i, nrow(child_individual_like_pos))
individual_emotion_data <- rbind(child_individual_like_pos, individual_emotion_data)
}
  
child_individual_want_pos <- data.frame(table(child_individual_want_pos$Age))
if (nrow(child_individual_want_pos) != 0){
names(child_individual_want_pos) <- c('Age', 'Freq')
child_individual_want_pos$Role <- rep('Child', nrow(child_individual_want_pos))
child_individual_want_pos$Head <- rep('want', nrow(child_individual_want_pos))
temp <- merge(child_individual_want_pos, subset(child_individual_descriptive, Child == i)[, -c(4)], by.x = 'Age', all.x = TRUE)
child_individual_want_pos <- temp
child_individual_want_pos$Total_ratio <- child_individual_want_pos$Freq / child_individual_want_pos$N_utterance
child_individual_want_pos$Ratio <- child_individual_want_pos$Freq / sum(child_individual_want_pos$Freq)
child_individual_want_pos$Polarity <- rep('positive', nrow(child_individual_want_pos))
child_individual_want_pos$Measure <- rep('positive construction ratio', nrow(child_individual_want_pos))
child_individual_want_pos$Which <- rep('ratio', nrow(child_individual_want_pos))
child_individual_want_pos$Function <- rep('Rejection', nrow(child_individual_want_pos))
child_individual_want_pos <- positive_moving(child_individual_want_pos, subset(child_individual_descriptive, Child == i))
child_individual_want_pos$Child <- rep(i, nrow(child_individual_want_pos))
individual_emotion_data <- rbind(child_individual_want_pos, individual_emotion_data)
}
  
parent_individual_like_pos <- data.frame(table(parent_individual_like_pos$Age))
  if (nrow(parent_individual_like_pos) != 0){
names(parent_individual_like_pos) <- c('Age', 'Freq')
parent_individual_like_pos$Role <- rep('Parent', nrow(parent_individual_like_pos))
parent_individual_like_pos$Head <- rep('like', nrow(parent_individual_like_pos))
temp <- merge(parent_individual_like_pos, subset(parent_individual_descriptive, Child == i)[, -c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_like_pos <- temp
parent_individual_like_pos$Total_ratio <- parent_individual_like_pos$Freq / parent_individual_like_pos$N_utterance
parent_individual_like_pos$Ratio <- parent_individual_like_pos$Freq / sum(parent_individual_like_pos$Freq)
parent_individual_like_pos$Polarity <- rep('positive', nrow(parent_individual_like_pos))
parent_individual_like_pos$Measure <- rep('positive construction ratio', nrow(parent_individual_like_pos))
parent_individual_like_pos$Which <- rep('ratio', nrow(parent_individual_like_pos))
parent_individual_like_pos$Function <- rep('Rejection', nrow(parent_individual_like_pos))
parent_individual_like_pos <- positive_moving(parent_individual_like_pos, subset(parent_individual_descriptive, Child == i))
parent_individual_like_pos$Child <- rep(i, nrow(parent_individual_like_pos))
individual_emotion_data <- rbind(parent_individual_like_pos, individual_emotion_data)
}
parent_individual_want_pos <- data.frame(table(parent_individual_want_pos$Age))
  if (nrow(parent_individual_want_pos) != 0){
names(parent_individual_want_pos) <- c('Age', 'Freq')
parent_individual_want_pos$Role <- rep('Parent', nrow(parent_individual_want_pos))
parent_individual_want_pos$Head <- rep('want', nrow(parent_individual_want_pos))
temp <- merge(parent_individual_want_pos, subset(parent_individual_descriptive, Child == i)[, -c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_want_pos <- temp
parent_individual_want_pos$Total_ratio <- parent_individual_want_pos$Freq / parent_individual_want_pos$N_utterance
parent_individual_want_pos$Ratio <- parent_individual_want_pos$Freq / sum(parent_individual_want_pos$Freq)
parent_individual_want_pos$Polarity <- rep('positive', nrow(parent_individual_want_pos))
parent_individual_want_pos$Measure <- rep('positive construction ratio', nrow(parent_individual_want_pos))
parent_individual_want_pos$Which <- rep('ratio', nrow(parent_individual_want_pos))
parent_individual_want_pos$Function <- rep('Rejection', nrow(parent_individual_want_pos))
parent_individual_want_pos <- positive_moving(parent_individual_want_pos, subset(parent_individual_descriptive, Child == i))
parent_individual_want_pos$Child <- rep(i, nrow(parent_individual_want_pos))
individual_emotion_data <- rbind(parent_individual_want_pos, individual_emotion_data)
  }
  
}

individual_emotion_data$Measure <- factor(individual_emotion_data$Measure, levels = c('negative construction ratio', 'negative construction moving ratio', 'positive construction ratio', 'positive construction moving ratio'))
individual_emotion_data <- subset(individual_emotion_data, Measure %in% c('negative construction moving ratio', 'positive construction moving ratio') & Child != '0')
individual_emotion_data_child <- subset(individual_emotion_data, Role == 'Child')
individual_emotion_data_parent <- subset(individual_emotion_data, Role == 'Parent')

for (i in emotion_children){
  child = i
  select <- data.frame(subset(individual_emotion_data_child, Child == i))
  if (nrow(select) != 0){
  summary <- data.frame(aggregate(Total_ratio~Age+Polarity, data = select, sum))
  summary$Freq <- rep(0, nrow(summary))
  summary$Role <- rep('Child', nrow(summary))
  summary$Head <- rep('combined', nrow(summary))
  summary$N_speaker <- rep(0, nrow(summary))
  summary$N_utterance <- rep(0, nrow(summary))
  summary$Ratio <- rep(0, nrow(summary))
  Measure <- as.vector(rep(0, nrow(summary)))
  for (z in 1:nrow(summary)){
    if (as.vector(summary$Polarity)[z] == 'negative'){
      Measure[z] = 'negative construction moving ratio'
    }
    
    if (as.vector(summary$Polarity)[z] == 'positive'){
      Measure[z] = 'positive construction moving ratio'
    }
  }
  print(Measure)
  summary$Measure <- Measure
  summary$Which <- rep('moving ratio', nrow(summary))
  summary$Function <- rep('Rejection', nrow(summary))
  summary$Child <- rep(child, nrow(summary))
  individual_emotion_data <- rbind(individual_emotion_data, summary)
}}

for (i in emotion_children){
  child = i
  select <- data.frame(subset(individual_emotion_data_parent, Child == i))
  if (nrow(select) != 0){
  summary <- data.frame(aggregate(Total_ratio~Age+Polarity, data = select, sum))
  summary$Freq <- rep(0, nrow(summary))
  summary$Role <- rep('Parent', nrow(summary))
  summary$Head <- rep('combined', nrow(summary))
  summary$N_speaker <- rep(0, nrow(summary))
  summary$N_utterance <- rep(0, nrow(summary))
  summary$Ratio <- rep(0, nrow(summary))
  Measure <- as.vector(rep(0, nrow(summary)))
  for (z in 1:nrow(summary)){
    if (as.vector(summary$Polarity)[z] == 'negative'){
      Measure[z] = 'negative construction moving ratio'
    }
    
    if (as.vector(summary$Polarity)[z] == 'positive'){
      Measure[z] = 'positive construction moving ratio'
    }
  }
  print(Measure)
  summary$Measure <- Measure
  summary$Which <- rep('moving ratio', nrow(summary))
  summary$Function <- rep('Rejection', nrow(summary))
  summary$Child <- rep(child, nrow(summary))
  individual_emotion_data <- rbind(individual_emotion_data, summary)
}}

individual_emotion_data_child <- subset(individual_emotion_data, Role == 'Child')
individual_emotion_data_parent <- subset(individual_emotion_data, Role == 'Parent')


```




```{r individualemotion, fig.env="figure", fig.pos = "H", fig.align = "center", fig.width=7, fig.height=9, set.cap.width=T, num.cols.cap=1, fig.cap='Individual Variation for  Rejection and its positive counterparts',warning=FALSE}

subset(individual_emotion_data, Head == 'combined') %>% 
  ggplot(aes(as.numeric(as.character(Age)), round(log(Total_ratio), 2), group = Measure, color = Measure)) +
  geom_line(aes(linetype=Measure), alpha = 1) +
  scale_linetype_manual(values=c("solid", 'solid')) +
  geom_point(aes(color = Measure, shape = Measure), size = 1) +
  scale_shape_manual(values = c(16, 16)) +
  scale_color_manual(values = c("steelblue", "mediumpurple4")) + 
  facet_grid( ~ Child ~ Role) +
  scale_x_continuous(breaks=seq(0, 72, 6)) +
  theme_classic() + 
  theme(text = element_text(size=12, family="Times")) + 
  theme(legend.position="top") +
  xlab("child age (months)") + 
  ylab("log(ratio)") + 
  guides(linetype = guide_legend(nrow = 1))

```


```{r individualperceptiondata, include=FALSE}

possession_children <- 0

children <- as.vector(unique(subset(perception, Age<=36)$Child))

for (i in 1:length(children)){
  select <- data.frame(subset(perception, Child == children[i] & Polarity == 'negative' & Role == 'Child' & Polarity == 'negative' & Function == 'possession' & grepl(' nan', children[i]) == FALSE))
    if (min(as.vector(unique(select$Age))) < 26 & as.numeric(length(unique(select$Age))) >= 8){#} & nrow(select) >= 80){
  possession_children = c(children[i], possession_children)
  }
}

possession_children = possession_children[1: length(possession_children) - 1]

individual_possession_data = 0

for (i in possession_children){
  
child_individual_possession_have_neg <- subset(child_perception_neg, Function %in% c('possession') & Head %in% c('have') & Child == i)
child_individual_possession_pro_neg <- subset(child_perception_neg, Function %in% c('possession') & Head != 'have' & Child == i)

parent_individual_possession_have_neg <- subset(parent_perception_neg, Function %in% c('possession') & Head %in% c('have') & Child == i)
parent_individual_possession_pro_neg <- subset(parent_perception_neg, Function %in% c('possession') & Head != 'have' & Child == i)

child_individual_possession_have_neg <- data.frame(table(child_individual_possession_have_neg$Age))

if (nrow(child_individual_possession_have_neg) != 0){
  
names(child_individual_possession_have_neg) <- c('Age', 'Freq')
child_individual_possession_have_neg$Role <- rep('Child', nrow(child_individual_possession_have_neg))
child_individual_possession_have_neg$Head <- rep('have', nrow(child_individual_possession_have_neg))
temp <- merge(child_individual_possession_have_neg, subset(child_individual_descriptive, Child ==i)[, -c(4)], by.x = 'Age', all.x = TRUE)
child_individual_possession_have_neg <- temp
child_individual_possession_have_neg$Total_ratio <- child_individual_possession_have_neg$Freq / child_individual_possession_have_neg$N_utterance
child_individual_possession_have_neg$Ratio <- child_individual_possession_have_neg$Freq / sum(child_individual_possession_have_neg$Freq)
child_individual_possession_have_neg$Polarity <- rep('negative', nrow(child_individual_possession_have_neg))
child_individual_possession_have_neg$Measure <- rep('negative construction ratio', nrow(child_individual_possession_have_neg))
child_individual_possession_have_neg$Which <- rep('ratio', nrow(child_individual_possession_have_neg))
child_individual_possession_have_neg$Function <- rep('Possession', nrow(child_individual_possession_have_neg))
child_individual_possession_have_neg <- negative_moving(child_individual_possession_have_neg, subset(child_individual_descriptive, Child == i))
child_individual_possession_have_neg$Child <- rep(i, nrow(child_individual_possession_have_neg))
individual_possession_data <- rbind(child_individual_possession_have_neg, individual_possession_data)
}

child_individual_possession_pro_neg <- data.frame(table(child_individual_possession_pro_neg$Age))

if (nrow(child_individual_possession_pro_neg) != 0){
  
names(child_individual_possession_pro_neg) <- c('Age', 'Freq')
child_individual_possession_pro_neg$Role <- rep('Child', nrow(child_individual_possession_pro_neg))
child_individual_possession_pro_neg$Head <- rep('pronoun', nrow(child_individual_possession_pro_neg))
temp <- merge(child_individual_possession_pro_neg, subset(child_individual_descriptive, Child == i)[, -c(4)], by.x = 'Age', all.x = TRUE)
child_individual_possession_pro_neg <- temp
child_individual_possession_pro_neg$Total_ratio <- child_individual_possession_pro_neg$Freq / child_individual_possession_pro_neg$N_utterance
child_individual_possession_pro_neg$Ratio <- child_individual_possession_pro_neg$Freq / sum(child_individual_possession_pro_neg$Freq)
child_individual_possession_pro_neg$Polarity <- rep('negative', nrow(child_individual_possession_pro_neg))
child_individual_possession_pro_neg$Measure <- rep('negative construction ratio', nrow(child_individual_possession_pro_neg))
child_individual_possession_pro_neg$Which <- rep('ratio', nrow(child_individual_possession_pro_neg))
child_individual_possession_pro_neg$Function <- rep('Possession', nrow(child_individual_possession_pro_neg))
child_individual_possession_pro_neg <- negative_moving(child_individual_possession_pro_neg, subset(child_individual_descriptive, Child == i))
child_individual_possession_pro_neg$Child <- rep(i, nrow(child_individual_possession_pro_neg))
individual_possession_data <- rbind(child_individual_possession_pro_neg, individual_possession_data)
}

parent_individual_possession_have_neg <- data.frame(table(parent_individual_possession_have_neg$Age))

if (nrow(parent_individual_possession_have_neg) != 0){
  
names(parent_individual_possession_have_neg) <- c('Age', 'Freq')
parent_individual_possession_have_neg$Role <- rep('Parent', nrow(parent_individual_possession_have_neg))
parent_individual_possession_have_neg$Head <- rep('have', nrow(parent_individual_possession_have_neg))
temp <- merge(parent_individual_possession_have_neg, subset(parent_individual_descriptive, Child == i)[, -c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_possession_have_neg <- temp
parent_individual_possession_have_neg$Total_ratio <- parent_individual_possession_have_neg$Freq / parent_individual_possession_have_neg$N_utterance
parent_individual_possession_have_neg$Ratio <- parent_individual_possession_have_neg$Freq / sum(parent_individual_possession_have_neg$Freq)
parent_individual_possession_have_neg$Polarity <- rep('negative', nrow(parent_individual_possession_have_neg))
parent_individual_possession_have_neg$Measure <- rep('negative construction ratio', nrow(parent_individual_possession_have_neg))
parent_individual_possession_have_neg$Which <- rep('ratio', nrow(parent_individual_possession_have_neg))
parent_individual_possession_have_neg$Function <- rep('Possession', nrow(parent_individual_possession_have_neg))
parent_individual_possession_have_neg <- negative_moving(parent_individual_possession_have_neg, subset(parent_individual_descriptive, Child == i))
parent_individual_possession_have_neg$Child <- rep(i, nrow(parent_individual_possession_have_neg))
individual_possession_data <- rbind(parent_individual_possession_have_neg, individual_possession_data)
}

parent_individual_possession_pro_neg <- data.frame(table(parent_individual_possession_pro_neg$Age))

if (nrow(parent_individual_possession_pro_neg) != 0){
  
names(parent_individual_possession_pro_neg) <- c('Age', 'Freq')
parent_individual_possession_pro_neg$Role <- rep('Parent', nrow(parent_individual_possession_pro_neg))
parent_individual_possession_pro_neg$Head <- rep('pronoun', nrow(parent_individual_possession_pro_neg))
temp <- merge(parent_individual_possession_pro_neg, subset(parent_individual_descriptive, Child == i)[, -c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_possession_pro_neg <- temp
parent_individual_possession_pro_neg$Total_ratio <- parent_individual_possession_pro_neg$Freq / parent_individual_possession_pro_neg$N_utterance
parent_individual_possession_pro_neg$Ratio <- parent_individual_possession_pro_neg$Freq / sum(parent_individual_possession_pro_neg$Freq)
parent_individual_possession_pro_neg$Polarity <- rep('negative', nrow(parent_individual_possession_pro_neg))
parent_individual_possession_pro_neg$Measure <- rep('negative construction ratio', nrow(parent_individual_possession_pro_neg))
parent_individual_possession_pro_neg$Which <- rep('ratio', nrow(parent_individual_possession_pro_neg))
parent_individual_possession_pro_neg$Function <- rep('Possession', nrow(parent_individual_possession_pro_neg))
parent_individual_possession_pro_neg <- negative_moving(parent_individual_possession_pro_neg, subset(parent_individual_descriptive, Child == i))
parent_individual_possession_pro_neg$Child <- rep(i, nrow(parent_individual_possession_pro_neg))
individual_possession_data <- rbind(parent_individual_possession_pro_neg, individual_possession_data)
}

child_individual_possession_have_pos <- subset(child_perception_pos, Function %in% c('possession') & Head %in% c('have') & Child == i)
child_individual_possession_pro_pos <- subset(child_perception_pos, Function %in% c('possession') & Head != 'have' & Child == i)

parent_individual_possession_have_pos <- subset(parent_perception_pos, Function %in% c('possession') & Head %in% c('have') & Child == i)
parent_individual_possession_pro_pos <- subset(parent_perception_pos, Function %in% c('possession') & Head != 'have' & Child == i)

child_individual_possession_have_pos <- data.frame(table(child_individual_possession_have_pos$Age))

if (nrow(child_individual_possession_have_pos) != 0){
  
names(child_individual_possession_have_pos) <- c('Age', 'Freq')
child_individual_possession_have_pos$Role <- rep('Child', nrow(child_individual_possession_have_pos))
child_individual_possession_have_pos$Head <- rep('have', nrow(child_individual_possession_have_pos))
temp <- merge(child_individual_possession_have_pos, subset(child_individual_descriptive, Child == i)[, -c(4)], by.x = 'Age', all.x = TRUE)
child_individual_possession_have_pos <- temp
child_individual_possession_have_pos$Total_ratio <- child_individual_possession_have_pos$Freq / child_individual_possession_have_pos$N_utterance
child_individual_possession_have_pos$Ratio <- child_individual_possession_have_pos$Freq / sum(child_individual_possession_have_pos$Freq)
child_individual_possession_have_pos$Polarity <- rep('positive', nrow(child_individual_possession_have_pos))
child_individual_possession_have_pos$Measure <- rep('positive construction ratio', nrow(child_individual_possession_have_pos))
child_individual_possession_have_pos$Which <- rep('ratio', nrow(child_individual_possession_have_pos))
child_individual_possession_have_pos$Function <- rep('Possession', nrow(child_individual_possession_have_pos))
child_individual_possession_have_pos <- positive_moving(child_individual_possession_have_pos, subset(child_individual_descriptive, Child == i))
child_individual_possession_have_pos$Child <- rep(i, nrow(child_individual_possession_have_pos))
individual_possession_data <- rbind(child_individual_possession_have_pos, individual_possession_data)
}

child_individual_possession_pro_pos <- data.frame(table(child_individual_possession_pro_pos$Age))

if (nrow(child_individual_possession_pro_pos) != 0){
  
names(child_individual_possession_pro_pos) <- c('Age', 'Freq')
child_individual_possession_pro_pos$Role <- rep('Child', nrow(child_individual_possession_pro_pos))
child_individual_possession_pro_pos$Head <- rep('pronoun', nrow(child_individual_possession_pro_pos))
temp <- merge(child_individual_possession_pro_pos, subset(child_individual_descriptive, Child == i)[, -c(4)], by.x = 'Age', all.x = TRUE)
child_individual_possession_pro_pos <- temp
child_individual_possession_pro_pos$Total_ratio <- child_individual_possession_pro_pos$Freq / child_individual_possession_pro_pos$N_utterance
child_individual_possession_pro_pos$Ratio <- child_individual_possession_pro_pos$Freq / sum(child_individual_possession_pro_pos$Freq)
child_individual_possession_pro_pos$Polarity <- rep('positive', nrow(child_individual_possession_pro_pos))
child_individual_possession_pro_pos$Measure <- rep('positive construction ratio', nrow(child_individual_possession_pro_pos))
child_individual_possession_pro_pos$Which <- rep('ratio', nrow(child_individual_possession_pro_pos))
child_individual_possession_pro_pos$Function <- rep('Possession', nrow(child_individual_possession_pro_pos))
child_individual_possession_pro_pos <- positive_moving(child_individual_possession_pro_pos, subset(child_individual_descriptive, Child == i))
child_individual_possession_pro_pos$Child <- rep(i, nrow(child_individual_possession_pro_pos))
individual_possession_data <- rbind(child_individual_possession_pro_pos, individual_possession_data)
}


parent_individual_possession_have_pos <- data.frame(table(parent_individual_possession_have_pos$Age))
if (nrow(parent_individual_possession_have_pos) != 0){
  
names(parent_individual_possession_have_pos) <- c('Age', 'Freq')
parent_individual_possession_have_pos$Role <- rep('Parent', nrow(parent_individual_possession_have_pos))
parent_individual_possession_have_pos$Head <- rep('have', nrow(parent_individual_possession_have_pos))
temp <- merge(parent_individual_possession_have_pos, subset(parent_individual_descriptive, Child ==i)[, -c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_possession_have_pos <- temp
parent_individual_possession_have_pos$Total_ratio <- parent_individual_possession_have_pos$Freq / parent_individual_possession_have_pos$N_utterance
parent_individual_possession_have_pos$Ratio <- parent_individual_possession_have_pos$Freq / sum(parent_individual_possession_have_pos$Freq)
parent_individual_possession_have_pos$Polarity <- rep('positive', nrow(parent_individual_possession_have_pos))
parent_individual_possession_have_pos$Measure <- rep('positive construction ratio', nrow(parent_individual_possession_have_pos))
parent_individual_possession_have_pos$Which <- rep('ratio', nrow(parent_individual_possession_have_pos))
parent_individual_possession_have_pos$Function <- rep('Possession', nrow(parent_individual_possession_have_pos))
parent_individual_possession_have_pos <- positive_moving(parent_individual_possession_have_pos, subset(parent_individual_descriptive, Child ==i))
parent_individual_possession_have_pos$Child <- rep(i, nrow(parent_individual_possession_have_pos))
individual_possession_data <- rbind(parent_individual_possession_have_pos, individual_possession_data)
}

parent_individual_possession_pro_pos <- data.frame(table(parent_individual_possession_pro_pos$Age))
if (nrow(parent_individual_possession_pro_pos) != 0){
  
names(parent_individual_possession_pro_pos) <- c('Age', 'Freq')
parent_individual_possession_pro_pos$Role <- rep('Parent', nrow(parent_individual_possession_pro_pos))
parent_individual_possession_pro_pos$Head <- rep('pronoun', nrow(parent_individual_possession_pro_pos))
temp <- merge(parent_individual_possession_pro_pos, subset(parent_individual_descriptive,  Child == i)[, -c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_possession_pro_pos <- temp
parent_individual_possession_pro_pos$Total_ratio <- parent_individual_possession_pro_pos$Freq / parent_individual_possession_pro_pos$N_utterance
parent_individual_possession_pro_pos$Ratio <- parent_individual_possession_pro_pos$Freq / sum(parent_individual_possession_pro_pos$Freq)
parent_individual_possession_pro_pos$Polarity <- rep('positive', nrow(parent_individual_possession_pro_pos))
parent_individual_possession_pro_pos$Measure <- rep('positive construction ratio', nrow(parent_individual_possession_pro_pos))
parent_individual_possession_pro_pos$Which <- rep('ratio', nrow(parent_individual_possession_pro_pos))
parent_individual_possession_pro_pos$Function <- rep('Possession', nrow(parent_individual_possession_pro_pos))
parent_individual_possession_pro_pos <- positive_moving(parent_individual_possession_pro_pos, subset(parent_individual_descriptive, Child == i))
parent_individual_possession_pro_pos$Child <- rep(i, nrow(parent_individual_possession_pro_pos))
individual_possession_data <- rbind(parent_individual_possession_pro_pos, individual_possession_data)
}}

individual_possession_data$Measure <- factor(individual_possession_data$Measure, levels = c('negative construction ratio', 'negative construction moving ratio', 'positive construction ratio', 'positive construction moving ratio'))
individual_possession_data <- subset(individual_possession_data, Measure %in% c('negative construction moving ratio', 'positive construction moving ratio') & Child != '0')

individual_possession_data_child <- subset(individual_possession_data, Role == 'Child')
individual_possession_data_parent <- subset(individual_possession_data, Role == 'Parent')

for (i in possession_children){
  child = i
  select <- data.frame(subset(individual_possession_data_child, Child == i))
  if (nrow(select) != 0){
  summary <- data.frame(aggregate(Total_ratio~Age+Polarity, data = select, sum))
  summary$Freq <- rep(0, nrow(summary))
  summary$Role <- rep('Child', nrow(summary))
  summary$Head <- rep('combined', nrow(summary))
  summary$N_speaker <- rep(0, nrow(summary))
  summary$N_utterance <- rep(0, nrow(summary))
  summary$Ratio <- rep(0, nrow(summary))
  Measure <- as.vector(rep(0, nrow(summary)))
  for (z in 1:nrow(summary)){
    if (as.vector(summary$Polarity)[z] == 'negative'){
      Measure[z] = 'negative construction moving ratio'
    }
    
    if (as.vector(summary$Polarity)[z] == 'positive'){
      Measure[z] = 'positive construction moving ratio'
    }
  }
  print(Measure)
  summary$Measure <- Measure
  summary$Which <- rep('moving ratio', nrow(summary))
  summary$Function <- rep('Possession', nrow(summary))
  summary$Child <- rep(child, nrow(summary))
  individual_possession_data <- rbind(individual_possession_data, summary)
}}

for (i in possession_children){
  child = i
  select <- data.frame(subset(individual_possession_data_parent, Child == i))
  if (nrow(select) != 0){
  summary <- data.frame(aggregate(Total_ratio~Age+Polarity, data = select, sum))
  summary$Freq <- rep(0, nrow(summary))
  summary$Role <- rep('Parent', nrow(summary))
  summary$Head <- rep('combined', nrow(summary))
  summary$N_speaker <- rep(0, nrow(summary))
  summary$N_utterance <- rep(0, nrow(summary))
  summary$Ratio <- rep(0, nrow(summary))
  Measure <- as.vector(rep(0, nrow(summary)))
  for (z in 1:nrow(summary)){
    if (as.vector(summary$Polarity)[z] == 'negative'){
      Measure[z] = 'negative construction moving ratio'
    }
    
    if (as.vector(summary$Polarity)[z] == 'positive'){
      Measure[z] = 'positive construction moving ratio'
    }
  }
  print(Measure)
  summary$Measure <- Measure
  summary$Which <- rep('moving ratio', nrow(summary))
  summary$Function <- rep('Possession', nrow(summary))
  summary$Child <- rep(child, nrow(summary))
  individual_possession_data <- rbind(individual_possession_data, summary)
  }}

individual_possession_data_child <- subset(individual_possession_data, Role == 'Child')
individual_possession_data_parent <- subset(individual_possession_data, Role == 'Parent')


existence_children = ''

children <- as.vector(unique(subset(perception, Age<=36)$Child))

for (i in 1:length(children)){
  select <- data.frame(subset(perception, Child == children[i] & Polarity == 'negative' & Role == 'Child' & Polarity == 'negative' & Function == 'existence' & grepl(' nan', children[i]) == FALSE))
    if (min(as.vector(unique(select$Age))) < 26 & as.numeric(length(unique(select$Age))) >= 8){#} & nrow(select) >= 80){
  existence_children = c(children[i], existence_children)
  }
}

existence_children = existence_children[1: length(existence_children) - 1]


individual_existence_data = 0


for (i in existence_children){
  
  child_individual_existence_neg <- subset(child_perception_neg, Function %in% c('existence') & Child == i)

parent_individual_existence_neg <- subset(parent_perception_neg, Function %in% c('existence') & Child == i)

child_individual_existence_neg <- data.frame(table(child_individual_existence_neg$Age))

if (nrow(child_individual_existence_neg) != 0){
names(child_individual_existence_neg) <- c('Age', 'Freq')
child_individual_existence_neg$Role <- rep('Child', nrow(child_individual_existence_neg))
child_individual_existence_neg$Head <- rep('', nrow(child_individual_existence_neg))
temp <- merge(child_individual_existence_neg, subset(child_individual_descriptive, Child == i)[, -c(4)], by.x = 'Age', all.x = TRUE)
child_individual_existence_neg <- temp
child_individual_existence_neg$Total_ratio <- child_individual_existence_neg$Freq / child_individual_existence_neg$N_utterance
child_individual_existence_neg$Ratio <- child_individual_existence_neg$Freq / sum(child_individual_existence_neg$Freq)
child_individual_existence_neg$Polarity <- rep('negative', nrow(child_individual_existence_neg))
child_individual_existence_neg$Measure <- rep('negative construction ratio', nrow(child_individual_existence_neg))
child_individual_existence_neg$Which <- rep('ratio', nrow(child_individual_existence_neg))
child_individual_existence_neg$Function <- rep('Non-existence', nrow(child_individual_existence_neg))
child_individual_existence_neg <- negative_moving(child_individual_existence_neg, subset(child_individual_descriptive, Child == i))
child_individual_existence_neg$Child <- rep(i, nrow(child_individual_existence_neg))
individual_existence_data <- rbind(child_individual_existence_neg, individual_existence_data)

}


parent_individual_existence_neg <- data.frame(table(parent_individual_existence_neg$Age))

if (nrow(parent_individual_existence_neg) != 0){
  
names(parent_individual_existence_neg) <- c('Age', 'Freq')
parent_individual_existence_neg$Role <- rep('Parent', nrow(parent_individual_existence_neg))
parent_individual_existence_neg$Head <- rep('existence', nrow(parent_individual_existence_neg))
temp <- merge(parent_individual_existence_neg, subset(parent_individual_descriptive, Child == i)[, -c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_existence_neg <- temp
parent_individual_existence_neg$Total_ratio <- parent_individual_existence_neg$Freq / parent_individual_existence_neg$N_utterance
parent_individual_existence_neg$Ratio <- parent_individual_existence_neg$Freq / sum(parent_individual_existence_neg$Freq)
parent_individual_existence_neg$Polarity <- rep('negative', nrow(parent_individual_existence_neg))
parent_individual_existence_neg$Measure <- rep('negative construction ratio', nrow(parent_individual_existence_neg))
parent_individual_existence_neg$Which <- rep('ratio', nrow(parent_individual_existence_neg))
parent_individual_existence_neg$Function <- rep('Non-existence', nrow(parent_individual_existence_neg))
parent_individual_existence_neg <- negative_moving(parent_individual_existence_neg, subset(parent_individual_descriptive, Child == i))
parent_individual_existence_neg$Child <- rep(i, nrow(parent_individual_existence_neg))
individual_existence_data <- rbind(parent_individual_existence_neg, individual_existence_data)

}

child_individual_existence_pos <- subset(child_perception_pos, Function %in% c('existence') & Child == i)

parent_individual_existence_pos <- subset(parent_perception_pos, Function %in% c('existence') & Child == i)


child_individual_existence_pos <- data.frame(table(child_individual_existence_pos$Age))

if (nrow(child_individual_existence_pos) != 0){
  
names(child_individual_existence_pos) <- c('Age', 'Freq')
child_individual_existence_pos$Role <- rep('Child', nrow(child_individual_existence_pos))
child_individual_existence_pos$Head <- rep('', nrow(child_individual_existence_pos))
temp <- merge(child_individual_existence_pos, subset(child_individual_descriptive, Child == i)[, -c(4)], by.x = 'Age', all.x = TRUE)
child_individual_existence_pos <- temp
child_individual_existence_pos$Total_ratio <- child_individual_existence_pos$Freq / child_individual_existence_pos$N_utterance
child_individual_existence_pos$Ratio <- child_individual_existence_pos$Freq / sum(child_individual_existence_pos$Freq)
child_individual_existence_pos$Polarity <- rep('positive', nrow(child_individual_existence_pos))
child_individual_existence_pos$Measure <- rep('positive construction ratio', nrow(child_individual_existence_pos))
child_individual_existence_pos$Which <- rep('ratio', nrow(child_individual_existence_pos))
child_individual_existence_pos$Function <- rep('Non-existence', nrow(child_individual_existence_pos))
child_individual_existence_pos <- positive_moving(child_individual_existence_pos, subset(child_individual_descriptive, Child == i))
child_individual_existence_pos$Child <- rep(i, nrow(child_individual_existence_pos))
individual_existence_data <- rbind(child_individual_existence_pos, individual_existence_data)

}


parent_individual_existence_pos <- data.frame(table(parent_individual_existence_pos$Age))

if (nrow(parent_individual_existence_pos) != 0){
  
names(parent_individual_existence_pos) <- c('Age', 'Freq')
parent_individual_existence_pos$Role <- rep('Parent', nrow(parent_individual_existence_pos))
parent_individual_existence_pos$Head <- rep('existence', nrow(parent_individual_existence_pos))
temp <- merge(parent_individual_existence_pos, subset(parent_individual_descriptive, Child == i)[, -c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_existence_pos <- temp
parent_individual_existence_pos$Total_ratio <- parent_individual_existence_pos$Freq / parent_individual_existence_pos$N_utterance
parent_individual_existence_pos$Ratio <- parent_individual_existence_pos$Freq / sum(parent_individual_existence_pos$Freq)
parent_individual_existence_pos$Polarity <- rep('positive', nrow(parent_individual_existence_pos))
parent_individual_existence_pos$Measure <- rep('positive construction ratio', nrow(parent_individual_existence_pos))
parent_individual_existence_pos$Which <- rep('ratio', nrow(parent_individual_existence_pos))
parent_individual_existence_pos$Function <- rep('Non-existence', nrow(parent_individual_existence_pos))
parent_individual_existence_pos <- positive_moving(parent_individual_existence_pos, subset(parent_individual_descriptive, Child ==i))
parent_individual_existence_pos$Child <- rep(i, nrow(parent_individual_existence_pos))
individual_existence_data <- rbind(parent_individual_existence_pos, individual_existence_data)

}}



individual_existence_data$Measure <- factor(individual_existence_data$Measure, levels = c('negative construction ratio', 'negative construction moving ratio', 'positive construction ratio', 'positive construction moving ratio'))

individual_existence_data <- subset(individual_existence_data, Measure %in% c('negative construction moving ratio', 'positive construction moving ratio') & Child != '0')


individual_existence_data_child <- subset(individual_existence_data, Role == 'Child')
individual_existence_data_parent <- subset(individual_existence_data, Role == 'Parent')


```



```{r individualexistence, fig.env="figure", fig.pos = "H", fig.align = "center", fig.width=7, fig.height=3, set.cap.width=T, num.cols.cap=1, fig.cap='Individual variation for Non-existence and its positive counterparts', warning=FALSE}

individual_existence_data %>% 
  ggplot(aes(as.numeric(as.character(Age)), round(log(Total_ratio), 2), group = Measure, color = Measure)) +
  geom_line(aes(linetype=Measure), alpha = 1) +
  scale_linetype_manual(values=c('solid', 'solid')) +
  geom_point(aes(color = Measure, shape = Measure), size = 1) +
  scale_shape_manual(values = c(16, 16)) +
  scale_color_manual(values = c("steelblue", "mediumpurple4")) + 
  facet_grid( ~ Child ~ Role ) +
  scale_x_continuous(breaks=seq(0, 72, 6)) +
  theme_classic() + 
  theme(text = element_text(size=12, family="Times")) + 
  theme(legend.position="top") +
  xlab("child age (months)") + 
  ylab("log(ratio)") + 
  guides(linetype = guide_legend(nrow = 1))

```





```{r individualmotordata, include=FALSE}

prohibition_children = ''

children <- as.vector(unique(subset(motor, Age<=36)$Child))

for (i in 1:length(children)){
  select <- data.frame(subset(motor, Child == children[i] & Polarity == 'negative' & Role == 'Child' & Function %in% c('prohibition') & grepl(' nan', children[i]) == FALSE))
    if (min(as.vector(unique(select$Age))) < 30 & as.numeric(as.numeric(length(unique(select$Age))) >= 8)){
  prohibition_children = c(children[i], prohibition_children)
  }
}

prohibition_children = prohibition_children[1: length(prohibition_children) - 1]


inability_children = ''

children <- as.vector(unique(subset(motor, Age<=36)$Child))

for (i in 1:length(children)){
  select <- data.frame(subset(motor, Child == children[i] & Polarity == 'negative' & Role == 'Child' & Function %in% c('inability') & grepl(' nan', children[i]) == FALSE))
    if (min(as.vector(unique(select$Age))) < 26 & as.numeric(length(unique(select$Age)) >= 8)){
  inability_children = c(children[i], inability_children)
  }
}

inability_children = inability_children[1: length(inability_children) - 1]

individual_prohibition_data = 0
individual_inability_data = 0


for (i in prohibition_children){
  
child_individual_prohibition_neg <- subset(child_motor_neg, Function %in% c('prohibition') & Child == i)

parent_individual_prohibition_neg <- subset(parent_motor_neg, Function %in% c('prohibition') & Child == i)


child_individual_prohibition_neg <- data.frame(table(child_individual_prohibition_neg$Age))

if (nrow(child_individual_prohibition_neg) != 0){
  
names(child_individual_prohibition_neg) <- c('Age', 'Freq')
child_individual_prohibition_neg$Role <- rep('Child', nrow(child_individual_prohibition_neg))
child_individual_prohibition_neg$Head <- rep('', nrow(child_individual_prohibition_neg))
temp <- merge(child_individual_prohibition_neg, subset(child_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
child_individual_prohibition_neg <- temp
child_individual_prohibition_neg$Total_ratio <- child_individual_prohibition_neg$Freq / child_individual_prohibition_neg$N_utterance
child_individual_prohibition_neg$Ratio <- child_individual_prohibition_neg$Freq / sum(child_individual_prohibition_neg$Freq)
child_individual_prohibition_neg$Polarity <- rep('negative', nrow(child_individual_prohibition_neg))
child_individual_prohibition_neg$Measure <- rep('negative construction ratio', nrow(child_individual_prohibition_neg))
child_individual_prohibition_neg$Which <- rep('ratio', nrow(child_individual_prohibition_neg))
child_individual_prohibition_neg$Function <- rep('Prohibition', nrow(child_individual_prohibition_neg))
child_individual_prohibition_neg <- negative_moving(child_individual_prohibition_neg, subset(child_individual_descriptive, Child == i))
child_individual_prohibition_neg$Child <- rep(i, nrow(child_individual_prohibition_neg))
individual_prohibition_data <- rbind(child_individual_prohibition_neg, individual_prohibition_data)

}


parent_individual_prohibition_neg <- data.frame(table(parent_individual_prohibition_neg$Age))

if (nrow(parent_individual_prohibition_neg) != 0){
  
names(parent_individual_prohibition_neg) <- c('Age', 'Freq')
parent_individual_prohibition_neg$Role <- rep('Parent', nrow(parent_individual_prohibition_neg))
parent_individual_prohibition_neg$Head <- rep('', nrow(parent_individual_prohibition_neg))
temp <- merge(parent_individual_prohibition_neg, subset(parent_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_prohibition_neg <- temp
parent_individual_prohibition_neg$Total_ratio <- parent_individual_prohibition_neg$Freq / parent_individual_prohibition_neg$N_utterance
parent_individual_prohibition_neg$Ratio <- parent_individual_prohibition_neg$Freq / sum(parent_individual_prohibition_neg$Freq)
parent_individual_prohibition_neg$Polarity <- rep('negative', nrow(parent_individual_prohibition_neg))
parent_individual_prohibition_neg$Measure <- rep('negative construction ratio', nrow(parent_individual_prohibition_neg))
parent_individual_prohibition_neg$Which <- rep('ratio', nrow(parent_individual_prohibition_neg))
parent_individual_prohibition_neg$Function <- rep('Prohibition', nrow(parent_individual_prohibition_neg))
parent_individual_prohibition_neg <- negative_moving(parent_individual_prohibition_neg, subset(parent_individual_descriptive, Child == i))
parent_individual_prohibition_neg$Child <- rep(i, nrow(parent_individual_prohibition_neg))
individual_prohibition_data <- rbind(parent_individual_prohibition_neg, individual_prohibition_data)

}


child_individual_prohibition_pos <- subset(child_motor_pos, Function %in% c('prohibition') & Child == i)

parent_individual_prohibition_pos <- subset(parent_motor_pos, Function %in% c('prohibition') & Child == i)


child_individual_prohibition_pos <- data.frame(table(child_individual_prohibition_pos$Age))

if (nrow(child_individual_prohibition_pos) != 0){
  
names(child_individual_prohibition_pos) <- c('Age', 'Freq')
child_individual_prohibition_pos$Role <- rep('Child', nrow(child_individual_prohibition_pos))
child_individual_prohibition_pos$Head <- rep('', nrow(child_individual_prohibition_pos))
temp <- merge(child_individual_prohibition_pos, subset(child_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
child_individual_prohibition_pos <- temp
child_individual_prohibition_pos$Total_ratio <- child_individual_prohibition_pos$Freq / child_individual_prohibition_pos$N_utterance
child_individual_prohibition_pos$Ratio <- child_individual_prohibition_pos$Freq / sum(child_individual_prohibition_pos$Freq)
child_individual_prohibition_pos$Polarity <- rep('positive', nrow(child_individual_prohibition_pos))
child_individual_prohibition_pos$Measure <- rep('positive construction ratio', nrow(child_individual_prohibition_pos))
child_individual_prohibition_pos$Which <- rep('ratio', nrow(child_individual_prohibition_pos))
child_individual_prohibition_pos$Function <- rep('Prohibition', nrow(child_individual_prohibition_pos))
child_individual_prohibition_pos <- positive_moving(child_individual_prohibition_pos, subset(child_individual_descriptive, Child == i))
child_individual_prohibition_pos$Child <- rep(i, nrow(child_individual_prohibition_pos))
individual_prohibition_data <- rbind(child_individual_prohibition_pos, individual_prohibition_data)

}


parent_individual_prohibition_pos <- data.frame(table(parent_individual_prohibition_pos$Age))

if (nrow(parent_individual_prohibition_pos)){
  
names(parent_individual_prohibition_pos) <- c('Age', 'Freq')
parent_individual_prohibition_pos$Role <- rep('Parent', nrow(parent_individual_prohibition_pos))
parent_individual_prohibition_pos$Head <- rep('', nrow(parent_individual_prohibition_pos))
temp <- merge(parent_individual_prohibition_pos, subset(parent_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_prohibition_pos <- temp
parent_individual_prohibition_pos$Total_ratio <- parent_individual_prohibition_pos$Freq / parent_individual_prohibition_pos$N_utterance
parent_individual_prohibition_pos$Ratio <- parent_individual_prohibition_pos$Freq / sum(parent_individual_prohibition_pos$Freq)
parent_individual_prohibition_pos$Polarity <- rep('positive', nrow(parent_individual_prohibition_pos))
parent_individual_prohibition_pos$Measure <- rep('positive construction ratio', nrow(parent_individual_prohibition_pos))
parent_individual_prohibition_pos$Which <- rep('ratio', nrow(parent_individual_prohibition_pos))
parent_individual_prohibition_pos$Function <- rep('Prohibition', nrow(parent_individual_prohibition_pos))
parent_individual_prohibition_pos <- positive_moving(parent_individual_prohibition_pos, subset(parent_individual_descriptive, Child == i))
parent_individual_prohibition_pos$Child <- rep(i, nrow(parent_individual_prohibition_pos))
individual_prohibition_data <- rbind(parent_individual_prohibition_pos, individual_prohibition_data)

}}


for (i in inability_children){

child_individual_inability_neg <- subset(child_motor_neg, Function %in% c('inability') & Subj %in% c('I', 'i') & Child == i)

parent_individual_inability_neg <- subset(parent_motor_neg, Function %in% c('inability') & Subj %in% c('I', 'i') & Child == i)


child_individual_inability_neg <- data.frame(table(child_individual_inability_neg$Age))

if (nrow(child_individual_inability_neg) != 0){
  
names(child_individual_inability_neg) <- c('Age', 'Freq')
child_individual_inability_neg$Role <- rep('Child', nrow(child_individual_inability_neg))
child_individual_inability_neg$Head <- rep('', nrow(child_individual_inability_neg))
temp <- merge(child_individual_inability_neg, subset(child_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
child_individual_inability_neg <- temp
child_individual_inability_neg$Total_ratio <- child_individual_inability_neg$Freq / child_individual_inability_neg$N_utterance
child_individual_inability_neg$Ratio <- child_individual_inability_neg$Freq / sum(child_individual_inability_neg$Freq)
child_individual_inability_neg$Polarity <- rep('negative', nrow(child_individual_inability_neg))
child_individual_inability_neg$Measure <- rep('negative construction ratio', nrow(child_individual_inability_neg))
child_individual_inability_neg$Which <- rep('ratio', nrow(child_individual_inability_neg))
child_individual_inability_neg$Function <- rep('Inability', nrow(child_individual_inability_neg))
child_individual_inability_neg <- negative_moving(child_individual_inability_neg, subset(child_individual_descriptive, Child == i))
child_individual_inability_neg$Child <- rep(i, nrow(child_individual_inability_neg))
individual_inability_data <- rbind(child_individual_inability_neg, individual_inability_data)

}


parent_individual_inability_neg <- data.frame(table(parent_individual_inability_neg$Age))

if (nrow(parent_individual_inability_neg) != 0){
  
names(parent_individual_inability_neg) <- c('Age', 'Freq')
parent_individual_inability_neg$Role <- rep('Parent', nrow(parent_individual_inability_neg))
parent_individual_inability_neg$Head <- rep('', nrow(parent_individual_inability_neg))
temp <- merge(parent_individual_inability_neg, subset(parent_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_inability_neg <- temp
parent_individual_inability_neg$Total_ratio <- parent_individual_inability_neg$Freq / parent_individual_inability_neg$N_utterance
parent_individual_inability_neg$Ratio <- parent_individual_inability_neg$Freq / sum(parent_individual_inability_neg$Freq)
parent_individual_inability_neg$Polarity <- rep('negative', nrow(parent_individual_inability_neg))
parent_individual_inability_neg$Measure <- rep('negative construction ratio', nrow(parent_individual_inability_neg))
parent_individual_inability_neg$Which <- rep('ratio', nrow(parent_individual_inability_neg))
parent_individual_inability_neg$Function <- rep('Inability', nrow(parent_individual_inability_neg))
parent_individual_inability_neg <- negative_moving(parent_individual_inability_neg, subset(parent_individual_descriptive, Child == i))
parent_individual_inability_neg$Child <- rep(i, nrow(parent_individual_inability_neg))
individual_inability_data <- rbind(parent_individual_inability_neg, individual_inability_data)

}

child_individual_inability_pos <- subset(child_motor_pos, Function %in% c('inability') & Subj %in% c('I', 'i') & Child == i)

parent_individual_inability_pos <- subset(parent_motor_pos, Function %in% c('inability') & Subj %in% c('I', 'i') & Child == i)


child_individual_inability_pos <- data.frame(table(child_individual_inability_pos$Age))

if (nrow(child_individual_inability_pos) != 0){
  
names(child_individual_inability_pos) <- c('Age', 'Freq')
child_individual_inability_pos$Role <- rep('Child', nrow(child_individual_inability_pos))
child_individual_inability_pos$Head <- rep('', nrow(child_individual_inability_pos))
temp <- merge(child_individual_inability_pos, subset(child_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
child_individual_inability_pos <- temp
child_individual_inability_pos$Total_ratio <- child_individual_inability_pos$Freq / child_individual_inability_pos$N_utterance
child_individual_inability_pos$Ratio <- child_individual_inability_pos$Freq / sum(child_individual_inability_pos$Freq)
child_individual_inability_pos$Polarity <- rep('positive', nrow(child_individual_inability_pos))
child_individual_inability_pos$Measure <- rep('positive construction ratio', nrow(child_individual_inability_pos))
child_individual_inability_pos$Which <- rep('ratio', nrow(child_individual_inability_pos))
child_individual_inability_pos$Function <- rep('Inability', nrow(child_individual_inability_pos))
child_individual_inability_pos <- positive_moving(child_individual_inability_pos, subset(child_individual_descriptive, Child == i))
child_individual_inability_pos$Child <- rep(i, nrow(child_individual_inability_pos))
individual_inability_data <- rbind(child_individual_inability_pos, individual_inability_data)

}


parent_individual_inability_pos <- data.frame(table(parent_individual_inability_pos$Age))

if (nrow(parent_individual_inability_pos) != 0){
  
names(parent_individual_inability_pos) <- c('Age', 'Freq')
parent_individual_inability_pos$Role <- rep('Parent', nrow(parent_individual_inability_pos))
parent_individual_inability_pos$Head <- rep('', nrow(parent_individual_inability_pos))
temp <- merge(parent_individual_inability_pos, subset(parent_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_inability_pos <- temp
parent_individual_inability_pos$Total_ratio <- parent_individual_inability_pos$Freq / parent_individual_inability_pos$N_utterance
parent_individual_inability_pos$Ratio <- parent_individual_inability_pos$Freq / sum(parent_individual_inability_pos$Freq)
parent_individual_inability_pos$Polarity <- rep('positive', nrow(parent_individual_inability_pos))
parent_individual_inability_pos$Measure <- rep('positive construction ratio', nrow(parent_individual_inability_pos))
parent_individual_inability_pos$Which <- rep('ratio', nrow(parent_individual_inability_pos))
parent_individual_inability_pos$Function <- rep('Inability', nrow(parent_individual_inability_pos))
parent_individual_inability_pos <- positive_moving(parent_individual_inability_pos, subset(parent_individual_descriptive, Child == i))
parent_individual_inability_pos$Child <- rep(i, nrow(parent_individual_inability_pos))
individual_inability_data <- rbind(parent_individual_inability_pos, individual_inability_data)

}}

individual_prohibition_data$Measure <- factor(individual_prohibition_data$Measure, levels = c('negative construction ratio', 'negative construction moving ratio', 'positive construction ratio', 'positive construction moving ratio'))

individual_prohibition_data <- subset(individual_prohibition_data, Measure %in% c('negative construction moving ratio', 'positive construction moving ratio') & Child != '0')

individual_inability_data$Measure <- factor(individual_inability_data$Measure, levels = c('negative construction ratio', 'negative construction moving ratio', 'positive construction ratio', 'positive construction moving ratio'))

individual_inability_data <- subset(individual_inability_data, Measure %in% c('negative construction moving ratio', 'positive construction moving ratio') & Child != '0')


individual_prohibition_data_child <- subset(individual_prohibition_data, Role =='Child')
individual_prohibition_data_parent <- subset(individual_prohibition_data, Role =='Parent')

individual_inability_data_child <- subset(individual_inability_data, Role =='Child')
individual_inability_data_parent <- subset(individual_inability_data, Role =='Parent')

```


```{r individualprohibition, fig.env="figure", fig.pos = "H", fig.align = "center", fig.width=7, fig.height=7, set.cap.width=T, num.cols.cap=1, fig.cap='Individual variation for Prohibition and its positive counterparts', warning=FALSE}

individual_prohibition_data %>% 
  ggplot(aes(as.numeric(as.character(Age)), round(log(Total_ratio), 2), group = Measure, color = Measure)) +
  geom_line(aes(linetype=Measure), alpha = 1) +
  scale_linetype_manual(values=c('solid', 'solid')) +
  geom_point(aes(color = Measure, shape = Measure), size = 1) +
  scale_shape_manual(values = c(16, 16)) +
  scale_color_manual(values = c("steelblue", "mediumpurple4")) +
  facet_grid( ~ Child ~ Role) +
  scale_x_continuous(breaks=seq(0, 72, 6)) +
  theme_classic() + 
  theme(text = element_text(size=12, family="Times")) + 
  theme(legend.position="top") +
  xlab("child age (months)") + 
  ylab("log(ratio)") + 
  ylim(-11, -2) +
  guides(linetype = guide_legend(nrow = 2))

```


```{r individualinability, fig.env="figure", fig.pos = "H", fig.align = "center", fig.width=7, fig.height=9, set.cap.width=T, num.cols.cap=1, fig.cap='Individual variation for Inability and its positive counterparts', warning=FALSE}

individual_inability_data %>% 
  ggplot(aes(as.numeric(as.character(Age)), round(log(Total_ratio), 2), group = Measure, color = Measure)) +
  geom_line(aes(linetype=Measure), alpha = 1) +
  scale_linetype_manual(values=c('solid', 'solid')) +
  geom_point(aes(color = Measure, shape = Measure), size = 1) +
  scale_shape_manual(values = c(16, 16)) +
  scale_color_manual(values = c("steelblue", "mediumpurple4")) +
  facet_grid( ~ Child ~ Role) +
  scale_x_continuous(breaks=seq(0, 72, 6)) +
  theme_classic() + 
  theme(text = element_text(size=12, family="Times")) + 
  theme(legend.position="top") +
  xlab("child age (months)") + 
  ylab("log(ratio)") + 
  ylim(-10, -2) +
  guides(linetype = guide_legend(nrow = 2))

```



```{r individuallearningdata, include=FALSE}

learning_children = ''

children <- as.vector(unique(subset(learning, Age<=36)$Child))

for (i in 1:length(children)){
  select <- data.frame(subset(learning, Child == children[i] & Polarity == 'negative' & Role == 'Child' & grepl(' nan', children[i]) == FALSE))
    if (min(as.vector(unique(select$Age))) < 26 & as.numeric(length(unique(select$Age))) >= 8){
  learning_children = c(children[i], learning_children)
  }
}

learning_children = learning_children[1: length(learning_children) - 1]


individual_learning_data <- 0

for (i in learning_children){

child_individual_learning_neg <- subset(learning_neg, Role == 'Child' & Child == i)
parent_individual_learning_neg <- subset(learning_neg, Role == 'Parent' & Child == i)


child_individual_learning_neg <- data.frame(table(child_individual_learning_neg$Age))

if (nrow(child_individual_learning_neg)){
  
names(child_individual_learning_neg) <- c('Age', 'Freq')
child_individual_learning_neg$Role <- rep('Child', nrow(child_individual_learning_neg))
child_individual_learning_neg$Head <- rep('', nrow(child_individual_learning_neg))
temp <- merge(child_individual_learning_neg, subset(child_individual_descriptive, Child == i)[, -c(4)], by.x = 'Age', all.x = TRUE)
child_individual_learning_neg <- temp
child_individual_learning_neg$Total_ratio <- child_individual_learning_neg$Freq / child_individual_learning_neg$N_utterance
child_individual_learning_neg$Ratio <- child_individual_learning_neg$Freq / sum(child_individual_learning_neg$Freq)
child_individual_learning_neg$Polarity <- rep('negative', nrow(child_individual_learning_neg))
child_individual_learning_neg$Measure <- rep('negative construction ratio', nrow(child_individual_learning_neg))
child_individual_learning_neg$Which <- rep('ratio', nrow(child_individual_learning_neg))
child_individual_learning_neg$Function <- rep('Labeling', nrow(child_individual_learning_neg))
child_individual_learning_neg <- negative_moving(child_individual_learning_neg, subset(child_individual_descriptive, Child == i))
child_individual_learning_neg$Child <- rep(i, nrow(child_individual_learning_neg))
individual_learning_data <- rbind(child_individual_learning_neg, individual_learning_data)

}


parent_individual_learning_neg <- data.frame(table(parent_individual_learning_neg$Age))

if (nrow(parent_individual_learning_neg) != 0){
  
names(parent_individual_learning_neg) <- c('Age', 'Freq')
parent_individual_learning_neg$Role <- rep('Parent', nrow(parent_individual_learning_neg))
parent_individual_learning_neg$Head <- rep('Learning', nrow(parent_individual_learning_neg))
temp <- merge(parent_individual_learning_neg, subset(parent_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_learning_neg <- temp
parent_individual_learning_neg$Total_ratio <- parent_individual_learning_neg$Freq / parent_individual_learning_neg$N_utterance
parent_individual_learning_neg$Ratio <- parent_individual_learning_neg$Freq / sum(parent_individual_learning_neg$Freq)
parent_individual_learning_neg$Polarity <- rep('negative', nrow(parent_individual_learning_neg))
parent_individual_learning_neg$Measure <- rep('negative construction ratio', nrow(parent_individual_learning_neg))
parent_individual_learning_neg$Which <- rep('ratio', nrow(parent_individual_learning_neg))
parent_individual_learning_neg$Function <- rep('Labeling', nrow(parent_individual_learning_neg))
parent_individual_learning_neg <- negative_moving(parent_individual_learning_neg, subset(parent_individual_descriptive, Child == i))
parent_individual_learning_neg$Child <- rep(i, nrow(parent_individual_learning_neg))
individual_learning_data <- rbind(parent_individual_learning_neg, individual_learning_data)

}

child_individual_learning_pos <- subset(learning_pos, Role == 'Child' & Child == i)
parent_individual_learning_pos <- subset(learning_pos, Role == 'Parent' & Child == i)


child_individual_learning_pos <- data.frame(table(child_individual_learning_pos$Age))

if (nrow(child_individual_learning_pos) != 0){
  
names(child_individual_learning_pos) <- c('Age', 'Freq')
child_individual_learning_pos$Role <- rep('Child', nrow(child_individual_learning_pos))
child_individual_learning_pos$Head <- rep('', nrow(child_individual_learning_pos))
temp <- merge(child_individual_learning_pos, subset(child_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
child_individual_learning_pos <- temp
child_individual_learning_pos$Total_ratio <- child_individual_learning_pos$Freq / child_individual_learning_pos$N_utterance
child_individual_learning_pos$Ratio <- child_individual_learning_pos$Freq / sum(child_individual_learning_pos$Freq)
child_individual_learning_pos$Polarity <- rep('positive', nrow(child_individual_learning_pos))
child_individual_learning_pos$Measure <- rep('positive construction ratio', nrow(child_individual_learning_pos))
child_individual_learning_pos$Which <- rep('ratio', nrow(child_individual_learning_pos))
child_individual_learning_pos$Function <- rep('Labeling', nrow(child_individual_learning_pos))
child_individual_learning_pos <- positive_moving(child_individual_learning_pos, subset(child_individual_descriptive, Child == i))
child_individual_learning_pos$Child <- rep(i, nrow(child_individual_learning_pos))
individual_learning_data <- rbind(child_individual_learning_pos, individual_learning_data)

}


parent_individual_learning_pos <- data.frame(table(parent_individual_learning_pos$Age))

if (nrow(parent_individual_learning_pos)){
  
names(parent_individual_learning_pos) <- c('Age', 'Freq')
parent_individual_learning_pos$Role <- rep('Parent', nrow(parent_individual_learning_pos))
parent_individual_learning_pos$Head <- rep('Learning', nrow(parent_individual_learning_pos))
temp <- merge(parent_individual_learning_pos, subset(parent_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_learning_pos <- temp
parent_individual_learning_pos$Total_ratio <- parent_individual_learning_pos$Freq / parent_individual_learning_pos$N_utterance
parent_individual_learning_pos$Ratio <- parent_individual_learning_pos$Freq / sum(parent_individual_learning_pos$Freq)
parent_individual_learning_pos$Polarity <- rep('positive', nrow(parent_individual_learning_pos))
parent_individual_learning_pos$Measure <- rep('positive construction ratio', nrow(parent_individual_learning_pos))
parent_individual_learning_pos$Which <- rep('ratio', nrow(parent_individual_learning_pos))
parent_individual_learning_pos$Function <- rep('Labeling', nrow(parent_individual_learning_pos))
parent_individual_learning_pos <- positive_moving(parent_individual_learning_pos, subset(parent_individual_descriptive, Child == i))
parent_individual_learning_pos$Child <- rep(i, nrow(parent_individual_learning_pos))
individual_learning_data <- rbind(parent_individual_learning_pos, individual_learning_data)

}}


individual_learning_data$Measure <- factor(individual_learning_data$Measure, levels = c('negative construction ratio', 'negative construction moving ratio', 'positive construction ratio', 'positive construction moving ratio'))

individual_learning_data <- subset(individual_learning_data, Measure %in% c('negative construction moving ratio', 'positive construction moving ratio') & Child != '0')

individual_learning_data_child <- subset(learning_data, Role == 'Child')
individual_learning_data_parent <- subset(learning_data, Role == 'Parent')


```


```{r individuallearning, fig.env="figure", fig.pos = "H", fig.align = "center", fig.width=7, fig.height=9, set.cap.width=T, num.cols.cap=1, fig.cap='Individual variation for Labeling and its positive counterparts', warning=FALSE}

individual_learning_data %>% 
  ggplot(aes(as.numeric(as.character(Age)), round(log(Total_ratio), 2), group = Measure, color = Measure)) +
  geom_line(aes(linetype=Measure), alpha = 1) +
  scale_linetype_manual(values=c('solid', 'solid')) +
  geom_point(aes(color = Measure, shape = Measure), size = 1) +
  scale_shape_manual(values = c(16, 16)) +
  scale_color_manual(values = c("steelblue", "mediumpurple4")) +
  facet_grid( ~ Child ~ Role) +
  scale_x_continuous(breaks=seq(0, 72, 6)) +
  theme_classic() + 
  theme(text = element_text(size=12, family="Times")) + 
  theme(legend.position="top") +
  xlab("child age (months)") + 
  ylab("log(ratio)") + 
  ylim(-10, -1.7) +
  guides(linetype = guide_legend(nrow = 1))

```

```{r individualepistemicdata, include=FALSE}

epistemic_children = ''

children <- as.vector(unique(subset(epistemic, Age<=36)$Child))

for (i in 1:length(children)){
  select <- data.frame(subset(epistemic, Child == children[i] & Polarity == 'negative' & Role == 'Child' & grepl(' nan', children[i]) == FALSE))
    if (min(as.vector(unique(select$Age))) < 26 & as.numeric(length(unique(select$Age))) >= 8){
  epistemic_children = c(children[i], epistemic_children)
  }
}

epistemic_children = epistemic_children[1: length(epistemic_children) - 1]


emotion_children = emotion_children[1: length(emotion_children) - 1]

individual_epistemic_data <- 0

for (i in epistemic_children){

#child_individual_epistemic_neg <- subset(epistemic_neg, Role %in% c('Child') & Child == i & Head %in% c('know', 'remember', 'think'))
#parent_individual_epistemic_neg <- subset(epistemic_neg, Role %in% c('Parent') & Child == i & Head %in% c('know', 'remember', 'think'))

child_individual_epistemic_neg <- subset(epistemic_neg, Role %in% c('Child') & Child == i)
parent_individual_epistemic_neg <- subset(epistemic_neg, Role %in% c('Parent') & Child == i)
child_individual_know_neg <- subset(child_individual_epistemic_neg, Head %in% c('know'))
child_individual_remember_neg <- subset(child_individual_epistemic_neg, Head %in% c('remember'))
child_individual_think_neg <- subset(child_individual_epistemic_neg, Head %in% c('think'))
parent_individual_know_neg <- subset(parent_individual_epistemic_neg, Head %in% c('know'))
parent_individual_remember_neg <- subset(parent_individual_epistemic_neg, Head %in% c('remember'))
parent_individual_think_neg <- subset(parent_individual_epistemic_neg, Head %in% c('think'))
child_individual_know_neg <- data.frame(table(child_individual_know_neg$Age))
if (nrow(child_individual_know_neg) != 0){
  
names(child_individual_know_neg) <- c('Age', 'Freq')
child_individual_know_neg$Role <- rep('Child', nrow(child_individual_know_neg))
child_individual_know_neg$Head <- rep('know', nrow(child_individual_know_neg))
temp <- merge(child_individual_know_neg, subset(child_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
child_individual_know_neg <- temp
child_individual_know_neg$Total_ratio <- child_individual_know_neg$Freq / child_individual_know_neg$N_utterance
child_individual_know_neg$Ratio <- child_individual_know_neg$Freq / sum(child_individual_know_neg$Freq)
child_individual_know_neg$Polarity <- rep('negative', nrow(child_individual_know_neg))
child_individual_know_neg$Measure <- rep('negative construction ratio', nrow(child_individual_know_neg))
child_individual_know_neg$Which <- rep('ratio', nrow(child_individual_know_neg))
child_individual_know_neg$Function <- rep('Epistemic', nrow(child_individual_know_neg))
child_individual_know_neg <- negative_moving(child_individual_know_neg, subset(child_individual_descriptive, Child == i))
child_individual_know_neg$Child <- rep(i, nrow(child_individual_know_neg))
individual_epistemic_data <- rbind(child_individual_know_neg, individual_epistemic_data)
}

child_individual_remember_neg <- data.frame(table(child_individual_remember_neg$Age))
if (nrow(child_individual_remember_neg) != 0){
  
names(child_individual_remember_neg) <- c('Age', 'Freq')
child_individual_remember_neg$Role <- rep('Child', nrow(child_individual_remember_neg))
child_individual_remember_neg$Head <- rep('remember', nrow(child_individual_remember_neg))
temp <- merge(child_individual_remember_neg, subset(child_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
child_individual_remember_neg <- temp
child_individual_remember_neg$Total_ratio <- child_individual_remember_neg$Freq / child_individual_remember_neg$N_utterance
child_individual_remember_neg$Ratio <- child_individual_remember_neg$Freq / sum(child_individual_remember_neg$Freq)
child_individual_remember_neg$Polarity <- rep('negative', nrow(child_individual_remember_neg))
child_individual_remember_neg$Measure <- rep('negative construction ratio', nrow(child_individual_remember_neg))
child_individual_remember_neg$Which <- rep('ratio', nrow(child_individual_remember_neg))
child_individual_remember_neg$Function <- rep('Epistemic', nrow(child_individual_remember_neg))
child_individual_remember_neg <- negative_moving(child_individual_remember_neg, subset(child_individual_descriptive, Child == i))
child_individual_remember_neg$Child <- rep(i, nrow(child_individual_remember_neg))
individual_epistemic_data <- rbind(child_individual_remember_neg, individual_epistemic_data)
}
child_individual_think_neg <- data.frame(table(child_individual_think_neg$Age))
if (nrow(child_individual_think_neg) != 0){
  
names(child_individual_think_neg) <- c('Age', 'Freq')
child_individual_think_neg$Role <- rep('Child', nrow(child_individual_think_neg))
child_individual_think_neg$Head <- rep('think', nrow(child_individual_think_neg))
temp <- merge(child_individual_think_neg, subset(child_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
child_individual_think_neg <- temp
child_individual_think_neg$Total_ratio <- child_individual_think_neg$Freq / child_individual_think_neg$N_utterance
child_individual_think_neg$Ratio <- child_individual_think_neg$Freq / sum(child_individual_think_neg$Freq)
child_individual_think_neg$Polarity <- rep('negative', nrow(child_individual_think_neg))
child_individual_think_neg$Measure <- rep('negative construction ratio', nrow(child_individual_think_neg))
child_individual_think_neg$Which <- rep('ratio', nrow(child_individual_think_neg))
child_individual_think_neg$Function <- rep('Epistemic', nrow(child_individual_think_neg))
child_individual_think_neg <- negative_moving(child_individual_think_neg, subset(child_individual_descriptive, Child == i))
child_individual_think_neg$Child <- rep(i, nrow(child_individual_think_neg))
individual_epistemic_data <- rbind(child_individual_think_neg, individual_epistemic_data)
}
parent_individual_know_neg <- data.frame(table(parent_individual_know_neg$Age))
if (nrow(parent_individual_know_neg)){
  
names(parent_individual_know_neg) <- c('Age', 'Freq')
parent_individual_know_neg$Role <- rep('Parent', nrow(parent_individual_know_neg))
parent_individual_know_neg$Head <- rep('know', nrow(parent_individual_know_neg))
temp <- merge(parent_individual_know_neg, subset(parent_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_know_neg <- temp
parent_individual_know_neg$Total_ratio <- parent_individual_know_neg$Freq / parent_individual_know_neg$N_utterance
parent_individual_know_neg$Ratio <- parent_individual_know_neg$Freq / sum(parent_individual_know_neg$Freq)
parent_individual_know_neg$Polarity <- rep('negative', nrow(parent_individual_know_neg))
parent_individual_know_neg$Measure <- rep('negative construction ratio', nrow(parent_individual_know_neg))
parent_individual_know_neg$Which <- rep('ratio', nrow(parent_individual_know_neg))
parent_individual_know_neg$Function <- rep('Epistemic', nrow(parent_individual_know_neg))
parent_individual_know_neg <- negative_moving(parent_individual_know_neg, subset(parent_individual_descriptive, Child == i))
parent_individual_know_neg$Child <- rep(i, nrow(parent_individual_know_neg))
individual_epistemic_data <- rbind(parent_individual_know_neg, individual_epistemic_data)
}
parent_individual_remember_neg <- data.frame(table(parent_individual_remember_neg$Age))
if (nrow(parent_individual_remember_neg) != 0){
  
names(parent_individual_remember_neg) <- c('Age', 'Freq')
parent_individual_remember_neg$Role <- rep('Parent', nrow(parent_individual_remember_neg))
parent_individual_remember_neg$Head <- rep('remember', nrow(parent_individual_remember_neg))
temp <- merge(parent_individual_remember_neg, subset(parent_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_remember_neg <- temp
parent_individual_remember_neg$Total_ratio <- parent_individual_remember_neg$Freq / parent_individual_remember_neg$N_utterance
parent_individual_remember_neg$Ratio <- parent_individual_remember_neg$Freq / sum(parent_individual_remember_neg$Freq)
parent_individual_remember_neg$Polarity <- rep('negative', nrow(parent_individual_remember_neg))
parent_individual_remember_neg$Measure <- rep('negative construction ratio', nrow(parent_individual_remember_neg))
parent_individual_remember_neg$Which <- rep('ratio', nrow(parent_individual_remember_neg))
parent_individual_remember_neg$Function <- rep('Epistemic', nrow(parent_individual_remember_neg))
parent_individual_remember_neg <- negative_moving(parent_individual_remember_neg, subset(parent_individual_descriptive, Child == i))
parent_individual_remember_neg$Child <- rep(i, nrow(parent_individual_remember_neg))
individual_epistemic_data <- rbind(parent_individual_remember_neg, individual_epistemic_data)
}
parent_individual_think_neg <- data.frame(table(parent_individual_think_neg$Age))
if (nrow(parent_individual_think_neg) != 0){
  
names(parent_individual_think_neg) <- c('Age', 'Freq')
parent_individual_think_neg$Role <- rep('Parent', nrow(parent_individual_think_neg))
parent_individual_think_neg$Head <- rep('think', nrow(parent_individual_think_neg))
temp <- merge(parent_individual_think_neg, subset(parent_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_think_neg <- temp
parent_individual_think_neg$Total_ratio <- parent_individual_think_neg$Freq / parent_individual_think_neg$N_utterance
parent_individual_think_neg$Ratio <- parent_individual_think_neg$Freq / sum(parent_individual_think_neg$Freq)
parent_individual_think_neg$Polarity <- rep('negative', nrow(parent_individual_think_neg))
parent_individual_think_neg$Measure <- rep('negative construction ratio', nrow(parent_individual_think_neg))
parent_individual_think_neg$Which <- rep('ratio', nrow(parent_individual_think_neg))
parent_individual_think_neg$Function <- rep('Epistemic', nrow(parent_individual_think_neg))
parent_individual_think_neg <- negative_moving(parent_individual_think_neg, subset(parent_individual_descriptive, Child == i))
parent_individual_think_neg$Child <- rep(i, nrow(parent_individual_think_neg))
individual_epistemic_data <- rbind(parent_individual_think_neg, individual_epistemic_data)
}
child_individual_epistemic_pos <- subset(epistemic_pos, Role %in% c('Child') & Child == i)
parent_individual_epistemic_pos <- subset(epistemic_pos, Role %in% c('Parent') & Child == i)
child_individual_know_pos <- subset(child_individual_epistemic_pos, Head %in% c('know'))
child_individual_remember_pos <- subset(child_individual_epistemic_pos, Head %in% c('remember'))
child_individual_think_pos <- subset(child_individual_epistemic_pos, Head %in% c('think'))
parent_individual_know_pos <- subset(parent_individual_epistemic_pos, Head %in% c('know'))
parent_individual_remember_pos <- subset(parent_individual_epistemic_pos, Head %in% c('remember'))
parent_individual_think_pos <- subset(parent_individual_epistemic_pos, Head %in% c('think'))
child_individual_know_pos <- data.frame(table(child_individual_know_pos$Age))
if (nrow(child_individual_know_pos) != 0){
  
names(child_individual_know_pos) <- c('Age', 'Freq')
child_individual_know_pos$Role <- rep('Child', nrow(child_individual_know_pos))
child_individual_know_pos$Head <- rep('know', nrow(child_individual_know_pos))
temp <- merge(child_individual_know_pos, subset(child_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
child_individual_know_pos <- temp
child_individual_know_pos$Total_ratio <- child_individual_know_pos$Freq / child_individual_know_pos$N_utterance
child_individual_know_pos$Ratio <- child_individual_know_pos$Freq / sum(child_individual_know_pos$Freq)
child_individual_know_pos$Polarity <- rep('positive', nrow(child_individual_know_pos))
child_individual_know_pos$Measure <- rep('positive construction ratio', nrow(child_individual_know_pos))
child_individual_know_pos$Which <- rep('ratio', nrow(child_individual_know_pos))
child_individual_know_pos$Function <- rep('Epistemic', nrow(child_individual_know_pos))
child_individual_know_pos <- positive_moving(child_individual_know_pos, subset(child_individual_descriptive, Child == i))
child_individual_know_pos$Child <- rep(i, nrow(child_individual_know_pos))
individual_epistemic_data <- rbind(child_individual_know_pos, individual_epistemic_data)
}
child_individual_remember_pos <- data.frame(table(child_individual_remember_pos$Age))
if (nrow(child_individual_remember_pos) != 0){
  
names(child_individual_remember_pos) <- c('Age', 'Freq')
child_individual_remember_pos$Role <- rep('Child', nrow(child_individual_remember_pos))
child_individual_remember_pos$Head <- rep('remember', nrow(child_individual_remember_pos))
temp <- merge(child_individual_remember_pos, subset(child_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
child_individual_remember_pos <- temp
child_individual_remember_pos$Total_ratio <- child_individual_remember_pos$Freq / child_individual_remember_pos$N_utterance
child_individual_remember_pos$Ratio <- child_individual_remember_pos$Freq / sum(child_individual_remember_pos$Freq)
child_individual_remember_pos$Polarity <- rep('positive', nrow(child_individual_remember_pos))
child_individual_remember_pos$Measure <- rep('positive construction ratio', nrow(child_individual_remember_pos))
child_individual_remember_pos$Which <- rep('ratio', nrow(child_individual_remember_pos))
child_individual_remember_pos$Function <- rep('Epistemic', nrow(child_individual_remember_pos))
child_individual_remember_pos <- positive_moving(child_individual_remember_pos, subset(child_individual_descriptive, Child == i))
child_individual_remember_pos$Child <- rep(i, nrow(child_individual_remember_pos))
individual_epistemic_data <- rbind(child_individual_remember_pos, individual_epistemic_data)
}
child_individual_think_pos <- data.frame(table(child_individual_think_pos$Age))
if (nrow(child_individual_think_pos)){
  
names(child_individual_think_pos) <- c('Age', 'Freq')
child_individual_think_pos$Role <- rep('Child', nrow(child_individual_think_pos))
child_individual_think_pos$Head <- rep('think', nrow(child_individual_think_pos))
temp <- merge(child_individual_think_pos, subset(child_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
child_individual_think_pos <- temp
child_individual_think_pos$Total_ratio <- child_individual_think_pos$Freq / child_individual_think_pos$N_utterance
child_individual_think_pos$Ratio <- child_individual_think_pos$Freq / sum(child_individual_think_pos$Freq)
child_individual_think_pos$Polarity <- rep('positive', nrow(child_individual_think_pos))
child_individual_think_pos$Measure <- rep('positive construction ratio', nrow(child_individual_think_pos))
child_individual_think_pos$Which <- rep('ratio', nrow(child_individual_think_pos))
child_individual_think_pos$Function <- rep('Epistemic', nrow(child_individual_think_pos))
child_individual_think_pos <- positive_moving(child_individual_think_pos, subset(child_individual_descriptive, Child == i))
child_individual_think_pos$Child <- rep(i, nrow(child_individual_think_pos))
individual_epistemic_data <- rbind(child_individual_think_pos, individual_epistemic_data)
}
parent_individual_know_pos <- data.frame(table(parent_individual_know_pos$Age))
if (nrow(parent_individual_know_pos)){
  
names(parent_individual_know_pos) <- c('Age', 'Freq')
parent_individual_know_pos$Role <- rep('Parent', nrow(parent_individual_know_pos))
parent_individual_know_pos$Head <- rep('know', nrow(parent_individual_know_pos))
temp <- merge(parent_individual_know_pos, subset(parent_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_know_pos <- temp
parent_individual_know_pos$Total_ratio <- parent_individual_know_pos$Freq / parent_individual_know_pos$N_utterance
parent_individual_know_pos$Ratio <- parent_individual_know_pos$Freq / sum(parent_individual_know_pos$Freq)
parent_individual_know_pos$Polarity <- rep('positive', nrow(parent_individual_know_pos))
parent_individual_know_pos$Measure <- rep('positive construction ratio', nrow(parent_individual_know_pos))
parent_individual_know_pos$Which <- rep('ratio', nrow(parent_individual_know_pos))
parent_individual_know_pos$Function <- rep('Epistemic', nrow(parent_individual_know_pos))
parent_individual_know_pos <- positive_moving(parent_individual_know_pos, subset(parent_individual_descriptive, Child == i))
parent_individual_know_pos$Child <- rep(i, nrow(parent_individual_know_pos))
individual_epistemic_data <- rbind(parent_individual_know_pos, individual_epistemic_data)
}
parent_individual_remember_pos <- data.frame(table(parent_individual_remember_pos$Age))
if (nrow(parent_individual_remember_pos) != 0){
  
names(parent_individual_remember_pos) <- c('Age', 'Freq')
parent_individual_remember_pos$Role <- rep('Parent', nrow(parent_individual_remember_pos))
parent_individual_remember_pos$Head <- rep('remember', nrow(parent_individual_remember_pos))
temp <- merge(parent_individual_remember_pos, subset(parent_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_remember_pos <- temp
parent_individual_remember_pos$Total_ratio <- parent_individual_remember_pos$Freq / parent_individual_remember_pos$N_utterance
parent_individual_remember_pos$Ratio <- parent_individual_remember_pos$Freq / sum(parent_individual_remember_pos$Freq)
parent_individual_remember_pos$Polarity <- rep('positive', nrow(parent_individual_remember_pos))
parent_individual_remember_pos$Measure <- rep('positive construction ratio', nrow(parent_individual_remember_pos))
parent_individual_remember_pos$Which <- rep('ratio', nrow(parent_individual_remember_pos))
parent_individual_remember_pos$Function <- rep('Epistemic', nrow(parent_individual_remember_pos))
parent_individual_remember_pos <- positive_moving(parent_individual_remember_pos, subset(parent_individual_descriptive, Child == i))
parent_individual_remember_pos$Child <- rep(i, nrow(parent_individual_remember_pos))
individual_epistemic_data <- rbind(parent_individual_remember_pos, individual_epistemic_data)
}
parent_individual_think_pos <- data.frame(table(parent_individual_think_pos$Age))
if (nrow(parent_individual_think_pos) != 0){
  
names(parent_individual_think_pos) <- c('Age', 'Freq')
parent_individual_think_pos$Role <- rep('Parent', nrow(parent_individual_think_pos))
parent_individual_think_pos$Head <- rep('think', nrow(parent_individual_think_pos))
temp <- merge(parent_individual_think_pos, subset(parent_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_think_pos <- temp
parent_individual_think_pos$Total_ratio <- parent_individual_think_pos$Freq / parent_individual_think_pos$N_utterance
parent_individual_think_pos$Ratio <- parent_individual_think_pos$Freq / sum(parent_individual_think_pos$Freq)
parent_individual_think_pos$Polarity <- rep('positive', nrow(parent_individual_think_pos))
parent_individual_think_pos$Measure <- rep('positive construction ratio', nrow(parent_individual_think_pos))
parent_individual_think_pos$Which <- rep('ratio', nrow(parent_individual_think_pos))
parent_individual_think_pos$Function <- rep('Epistemic', nrow(parent_individual_think_pos))
parent_individual_think_pos <- positive_moving(parent_individual_think_pos, subset(parent_individual_descriptive, Child == i))
parent_individual_think_pos$Child <- rep(i, nrow(parent_individual_think_pos))
individual_epistemic_data <- rbind(parent_individual_think_pos, individual_epistemic_data)

}}

individual_epistemic_data$Measure <- factor(individual_epistemic_data$Measure, levels = c('negative construction ratio', 'negative construction moving ratio', 'positive construction ratio', 'positive construction moving ratio'))
individual_epistemic_data <- subset(individual_epistemic_data, Measure %in% c('negative construction moving ratio', 'positive construction moving ratio') & Child != '0')
individual_epistemic_data_child <- subset(individual_epistemic_data, Role == 'Child')
individual_epistemic_data_parent <- subset(individual_epistemic_data, Role == 'Parent')


for (i in epistemic_children){
  child = i
  select <- data.frame(subset(individual_epistemic_data_child, Child == i))
  if (nrow(select) != 0){
  summary <- data.frame(aggregate(Total_ratio~Age+Polarity, data = select, sum))
  summary$Freq <- rep(0, nrow(summary))
  summary$Role <- rep('Child', nrow(summary))
  summary$Head <- rep('combined', nrow(summary))
  summary$N_speaker <- rep(0, nrow(summary))
  summary$N_utterance <- rep(0, nrow(summary))
  summary$Ratio <- rep(0, nrow(summary))
  Measure <- as.vector(rep(0, nrow(summary)))
  for (z in 1:nrow(summary)){
    if (as.vector(summary$Polarity)[z] == 'negative'){
      Measure[z] = 'negative construction moving ratio'
    }
    
    if (as.vector(summary$Polarity)[z] == 'positive'){
      Measure[z] = 'positive construction moving ratio'
    }
  }
  print(Measure)
  summary$Measure <- Measure
  summary$Which <- rep('moving ratio', nrow(summary))
  summary$Function <- rep('Epistemic', nrow(summary))
  summary$Child <- rep(child, nrow(summary))
  individual_epistemic_data <- rbind(individual_epistemic_data, summary)
}}

for (i in epistemic_children){
  child = i
  select <- data.frame(subset(individual_epistemic_data_parent, Child == i))
  if (nrow(select) != 0){
  summary <- data.frame(aggregate(Total_ratio~Age+Polarity, data = select, sum))
  summary$Freq <- rep(0, nrow(summary))
  summary$Role <- rep('Parent', nrow(summary))
  summary$Head <- rep('combined', nrow(summary))
  summary$N_speaker <- rep(0, nrow(summary))
  summary$N_utterance <- rep(0, nrow(summary))
  summary$Ratio <- rep(0, nrow(summary))
  Measure <- as.vector(rep(0, nrow(summary)))
  for (z in 1:nrow(summary)){
    if (as.vector(summary$Polarity)[z] == 'negative'){
      Measure[z] = 'negative construction moving ratio'
    }
    
    if (as.vector(summary$Polarity)[z] == 'positive'){
      Measure[z] = 'positive construction moving ratio'
    }
  }
  summary$Measure <- Measure
  summary$Which <- rep('moving ratio', nrow(summary))
  summary$Function <- rep('Epistemic', nrow(summary))
  summary$Child <- rep(child, nrow(summary))
  individual_epistemic_data <- rbind(individual_epistemic_data, summary)
}}

individual_epistemic_data_child <- subset(individual_epistemic_data, Role == 'Child')
individual_epistemic_data_parent <- subset(individual_epistemic_data, Role == 'Parent')

```


```{r individualepistemic, fig.env="figure", fig.pos = "H", fig.align = "center", fig.width=7, fig.height=9, set.cap.width=T, num.cols.cap=1, fig.cap='Individual variation for Epistemic negation and its positive counterparts', warning=FALSE}


subset(individual_epistemic_data, Head == 'combined') %>% 
  ggplot(aes(as.numeric(as.character(Age)), round(log(Total_ratio), 2), group = Measure, color = Measure)) +
  geom_line(aes(linetype=Measure), alpha = 1) +
  scale_linetype_manual(values=c('solid', 'solid')) +
  geom_point(aes(color = Measure, shape = Measure), size = 1) +
  scale_shape_manual(values = c(16, 16)) +
  scale_color_manual(values = c("steelblue", "mediumpurple4")) +
  facet_grid(  ~ Child ~ Role) +
  scale_x_continuous(breaks=seq(0, 72, 6)) +
  theme_classic() + 
  theme(text = element_text(size=12, family="Times")) + 
  theme(legend.position="top") +
  xlab("child age (months)") + 
  ylab("log(ratio)") + 
  guides(linetype = guide_legend(nrow = 1))

```

```{r individualpossession, fig.env="figure", fig.pos = "H", fig.align = "center", fig.width=7, fig.height=9, set.cap.width=T, num.cols.cap=1, fig.cap='Individual variation for Possession and its positive counterparts', warning=FALSE}


individual_possession_data %>% 
  ggplot(aes(as.numeric(as.character(Age)), round(log(Total_ratio), 2), group = Measure, color = Measure)) +
  geom_line(aes(linetype=Measure), alpha = 1) +
  scale_linetype_manual(values=c('solid','solid')) +
  geom_point(aes(color = Measure, shape = Measure), size = 1) +
  scale_shape_manual(values = c(16, 16)) +
  scale_color_manual(values = c("steelblue", "mediumpurple4")) +
  facet_grid( ~ Child ~ Role) +
  scale_x_continuous(breaks=seq(0, 72, 6)) +
  theme_classic() + 
  theme(text = element_text(size=12, family="Times")) + 
  theme(legend.position="top") +
  xlab("child age (months)") + 
  ylab("log(ratio)") + 
  guides(linetype = guide_legend(nrow = 1))

```



<!--

emotion_like_children = ''

children <- as.vector(unique(subset(emotion, Age<=36)$Child))

for (i in 1:length(children)){
  select <- data.frame(subset(emotion, Child == children[i] & Polarity == 'negative' & Role == 'Child' & Head %in% c('like') & grepl(' nan', children[i]) == FALSE))
    if (min(as.vector(unique(select$Age))) < 26 & as.numeric(length(unique(select$Age))) >= 8){
  emotion_like_children = c(children[i], emotion_like_children)
  }
}

emotion_like_children = emotion_like_children[1: length(emotion_like_children) - 1]

emotion_want_children = ''

children <- as.vector(unique(subset(emotion, Age<=36)$Child))

for (i in 1:length(children)){
  select <- data.frame(subset(emotion, Child == children[i] & Polarity == 'negative' & Role == 'Child' & Head %in% c('want') & grepl(' nan', children[i]) == FALSE))
    if (min(as.vector(unique(select$Age))) < 26 & as.numeric(length(unique(select$Age))) >= 8){
  emotion_want_children = c(children[i], emotion_want_children)
  }
}

emotion_want_children = emotion_want_children[1: length(emotion_want_children) - 1]

individual_emotion_like_data = 0
individual_emotion_want_data = 0

for (i in emotion_like_children){

  child_individual_like_neg <- subset(child_emotion_neg, Head %in% c('like') & Child == i)
  parent_individual_like_neg <- subset(parent_emotion_neg, Head %in% c('like') & Child == i)

  child_individual_like_pos <- subset(child_emotion_pos, Head %in% c('like') & Child == i)
  parent_individual_like_pos <- subset(parent_emotion_pos, Head %in% c('like') & Child == i)
  
  child_individual_like_neg <- data.frame(table(child_individual_like_neg$Age))
  
  if (nrow(child_individual_like_neg) != 0){
  names(child_individual_like_neg) <- c('Age', 'Freq')
  child_individual_like_neg$Role <- rep('Child', nrow(child_individual_like_neg))
  child_individual_like_neg$Head <- rep('like', nrow(child_individual_like_neg))
  temp <- merge(child_individual_like_neg, subset(child_individual_descriptive, Child == i)[, -c(4)], by.x = 'Age', all.x = TRUE)
  child_individual_like_neg <- temp
  child_individual_like_neg$Total_ratio <- child_individual_like_neg$Freq /    child_individual_like_neg$N_utterance
child_individual_like_neg$Ratio <- child_individual_like_neg$Freq / sum(child_individual_like_neg$Freq)
child_individual_like_neg$Polarity <- rep('negative', nrow(child_individual_like_neg))
child_individual_like_neg$Measure <- rep('negative construction ratio', nrow(child_individual_like_neg))
child_individual_like_neg$Which <- rep('ratio', nrow(child_individual_like_neg))
child_individual_like_neg$Function <- rep('Rejection', nrow(child_individual_like_neg))
child_individual_like_neg <- negative_moving(child_individual_like_neg, subset(child_individual_descriptive, Child == i))
child_individual_like_neg$Child <- rep(i, nrow(child_individual_like_neg))
individual_emotion_like_data <- rbind(child_individual_like_neg, individual_emotion_like_data)

}
  

parent_individual_like_neg <- data.frame(table(parent_individual_like_neg$Age))

  if (nrow(parent_individual_like_neg) != 0){
names(parent_individual_like_neg) <- c('Age', 'Freq')
parent_individual_like_neg$Role <- rep('Parent', nrow(parent_individual_like_neg))
parent_individual_like_neg$Head <- rep('like', nrow(parent_individual_like_neg))
temp <- merge(parent_individual_like_neg, subset(parent_individual_descriptive, Child == i)[, -c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_like_neg <- temp
parent_individual_like_neg$Total_ratio <- parent_individual_like_neg$Freq / parent_individual_like_neg$N_utterance
parent_individual_like_neg$Ratio <- parent_individual_like_neg$Freq / sum(parent_individual_like_neg$Freq)
parent_individual_like_neg$Polarity <- rep('negative', nrow(parent_individual_like_neg))
parent_individual_like_neg$Measure <- rep('negative construction ratio', nrow(parent_individual_like_neg))
parent_individual_like_neg$Which <- rep('ratio', nrow(parent_individual_like_neg))
parent_individual_like_neg$Function <- rep('Rejection', nrow(parent_individual_like_neg))
parent_individual_like_neg <- negative_moving(parent_individual_like_neg, subset(parent_individual_descriptive, Child == i))
parent_individual_like_neg$Child <- rep(i, nrow(parent_individual_like_neg))
individual_emotion_like_data <- rbind(parent_individual_like_neg, individual_emotion_like_data)

  }
  

child_individual_like_pos <- data.frame(table(child_individual_like_pos$Age))

if (nrow(child_individual_like_pos) != 0){
names(child_individual_like_pos) <- c('Age', 'Freq')
child_individual_like_pos$Role <- rep('Child', nrow(child_individual_like_pos))
child_individual_like_pos$Head <- rep('like', nrow(child_individual_like_pos))
temp <- merge(child_individual_like_pos, subset(child_individual_descriptive, Child == i)[, -c(4)], by.x = 'Age', all.x = TRUE)
child_individual_like_pos <- temp
child_individual_like_pos$Total_ratio <- child_individual_like_pos$Freq / child_individual_like_pos$N_utterance
child_individual_like_pos$Ratio <- child_individual_like_pos$Freq / sum(child_individual_like_pos$Freq)
child_individual_like_pos$Polarity <- rep('positive', nrow(child_individual_like_pos))
child_individual_like_pos$Measure <- rep('positive construction ratio', nrow(child_individual_like_pos))
child_individual_like_pos$Which <- rep('ratio', nrow(child_individual_like_pos))
child_individual_like_pos$Function <- rep('Rejection', nrow(child_individual_like_pos))
child_individual_like_pos <- positive_moving(child_individual_like_pos, subset(child_individual_descriptive, Child == i))
child_individual_like_pos$Child <- rep(i, nrow(child_individual_like_pos))
individual_emotion_like_data <- rbind(child_individual_like_pos, individual_emotion_like_data)

}

parent_individual_like_pos <- data.frame(table(parent_individual_like_pos$Age))

  if (nrow(parent_individual_like_pos) != 0){
names(parent_individual_like_pos) <- c('Age', 'Freq')
parent_individual_like_pos$Role <- rep('Parent', nrow(parent_individual_like_pos))
parent_individual_like_pos$Head <- rep('like', nrow(parent_individual_like_pos))
temp <- merge(parent_individual_like_pos, subset(parent_individual_descriptive, Child == i)[, -c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_like_pos <- temp
parent_individual_like_pos$Total_ratio <- parent_individual_like_pos$Freq / parent_individual_like_pos$N_utterance
parent_individual_like_pos$Ratio <- parent_individual_like_pos$Freq / sum(parent_individual_like_pos$Freq)
parent_individual_like_pos$Polarity <- rep('positive', nrow(parent_individual_like_pos))
parent_individual_like_pos$Measure <- rep('positive construction ratio', nrow(parent_individual_like_pos))
parent_individual_like_pos$Which <- rep('ratio', nrow(parent_individual_like_pos))
parent_individual_like_pos$Function <- rep('Rejection', nrow(parent_individual_like_pos))
parent_individual_like_pos <- positive_moving(parent_individual_like_pos, subset(parent_individual_descriptive, Child == i))
parent_individual_like_pos$Child <- rep(i, nrow(parent_individual_like_pos))
individual_emotion_like_data <- rbind(parent_individual_like_pos, individual_emotion_like_data)

}}

for (i in emotion_want_children){

    child_individual_want_neg <- subset(child_emotion_neg, Head %in% c('want') & Child == i)

  parent_individual_want_neg <- subset(parent_emotion_neg, Head %in% c('want') & Child == i)
  
   child_individual_want_pos <- subset(child_emotion_pos, Head %in% c('want') & Child == i)

  parent_individual_want_pos <- subset(parent_emotion_pos, Head %in% c('want') & Child == i)

child_individual_want_neg <- data.frame(table(child_individual_want_neg$Age))

  if (nrow(child_individual_want_neg) != 0){
names(child_individual_want_neg) <- c('Age', 'Freq')
child_individual_want_neg$Role <- rep('Child', nrow(child_individual_want_neg))
child_individual_want_neg$Head <- rep('want', nrow(child_individual_want_neg))
temp <- merge(child_individual_want_neg, subset(child_individual_descriptive, Child == i)[, -c(4)], by.x = 'Age', all.x = TRUE)
child_individual_want_neg <- temp
child_individual_want_neg$Total_ratio <- child_individual_want_neg$Freq / child_individual_want_neg$N_utterance
child_individual_want_neg$Ratio <- child_individual_want_neg$Freq / sum(child_individual_want_neg$Freq)
child_individual_want_neg$Polarity <- rep('negative', nrow(child_individual_want_neg))
child_individual_want_neg$Measure <- rep('negative construction ratio', nrow(child_individual_want_neg))
child_individual_want_neg$Which <- rep('ratio', nrow(child_individual_want_neg))
child_individual_want_neg$Function <- rep('Rejection', nrow(child_individual_want_neg))
child_individual_want_neg <- negative_moving(child_individual_want_neg, subset(child_individual_descriptive, Child == i))
child_individual_want_neg$Child <- rep(i, nrow(child_individual_want_neg))
individual_emotion_want_data <- rbind(child_individual_want_neg, individual_emotion_want_data)

}
  

parent_individual_want_neg <- data.frame(table(parent_individual_want_neg$Age))

if (nrow(parent_individual_want_neg) != 0){
names(parent_individual_want_neg) <- c('Age', 'Freq')
parent_individual_want_neg$Role <- rep('Parent', nrow(parent_individual_want_neg))
parent_individual_want_neg$Head <- rep('want', nrow(parent_individual_want_neg))
temp <- merge(parent_individual_want_neg, subset(parent_individual_descriptive, Child == i)[, -c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_want_neg <- temp
parent_individual_want_neg$Total_ratio <- parent_individual_want_neg$Freq / parent_individual_want_neg$N_utterance
parent_individual_want_neg$Ratio <- parent_individual_want_neg$Freq / sum(parent_individual_want_neg$Freq)
parent_individual_want_neg$Polarity <- rep('negative', nrow(parent_individual_want_neg))
parent_individual_want_neg$Measure <- rep('negative construction ratio', nrow(parent_individual_want_neg))
parent_individual_want_neg$Which <- rep('ratio', nrow(parent_individual_want_neg))
parent_individual_want_neg$Function <- rep('Rejection', nrow(parent_individual_want_neg))
parent_individual_want_neg <- negative_moving(parent_individual_want_neg, subset(parent_individual_descriptive, Child == i))
parent_individual_want_neg$Child <- rep(i, nrow(parent_individual_want_neg))
individual_emotion_want_data <- rbind(parent_individual_want_neg, individual_emotion_want_data)

}
  

child_individual_want_pos <- data.frame(table(child_individual_want_pos$Age))

if (nrow(child_individual_want_pos) != 0){
names(child_individual_want_pos) <- c('Age', 'Freq')
child_individual_want_pos$Role <- rep('Child', nrow(child_individual_want_pos))
child_individual_want_pos$Head <- rep('want', nrow(child_individual_want_pos))
temp <- merge(child_individual_want_pos, subset(child_individual_descriptive, Child == i)[, -c(4)], by.x = 'Age', all.x = TRUE)
child_individual_want_pos <- temp
child_individual_want_pos$Total_ratio <- child_individual_want_pos$Freq / child_individual_want_pos$N_utterance
child_individual_want_pos$Ratio <- child_individual_want_pos$Freq / sum(child_individual_want_pos$Freq)
child_individual_want_pos$Polarity <- rep('positive', nrow(child_individual_want_pos))
child_individual_want_pos$Measure <- rep('positive construction ratio', nrow(child_individual_want_pos))
child_individual_want_pos$Which <- rep('ratio', nrow(child_individual_want_pos))
child_individual_want_pos$Function <- rep('Rejection', nrow(child_individual_want_pos))
child_individual_want_pos <- positive_moving(child_individual_want_pos, subset(child_individual_descriptive, Child == i))
child_individual_want_pos$Child <- rep(i, nrow(child_individual_want_pos))
individual_emotion_want_data <- rbind(child_individual_want_pos, individual_emotion_want_data)

}

parent_individual_want_pos <- data.frame(table(parent_individual_want_pos$Age))

  if (nrow(parent_individual_want_pos) != 0){
names(parent_individual_want_pos) <- c('Age', 'Freq')
parent_individual_want_pos$Role <- rep('Parent', nrow(parent_individual_want_pos))
parent_individual_want_pos$Head <- rep('want', nrow(parent_individual_want_pos))
temp <- merge(parent_individual_want_pos, subset(parent_individual_descriptive, Child == i)[, -c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_want_pos <- temp
parent_individual_want_pos$Total_ratio <- parent_individual_want_pos$Freq / parent_individual_want_pos$N_utterance
parent_individual_want_pos$Ratio <- parent_individual_want_pos$Freq / sum(parent_individual_want_pos$Freq)
parent_individual_want_pos$Polarity <- rep('positive', nrow(parent_individual_want_pos))
parent_individual_want_pos$Measure <- rep('positive construction ratio', nrow(parent_individual_want_pos))
parent_individual_want_pos$Which <- rep('ratio', nrow(parent_individual_want_pos))
parent_individual_want_pos$Function <- rep('Rejection', nrow(parent_individual_want_pos))
parent_individual_want_pos <- positive_moving(parent_individual_want_pos, subset(parent_individual_descriptive, Child == i))
parent_individual_want_pos$Child <- rep(i, nrow(parent_individual_want_pos))
individual_emotion_want_data <- rbind(parent_individual_want_pos, individual_emotion_want_data)

}}

individual_emotion_like_data$Measure <- factor(individual_emotion_like_data$Measure, levels = c('negative construction ratio', 'negative construction moving ratio', 'positive construction ratio', 'positive construction moving ratio'))


individual_emotion_like_data <- subset(individual_emotion_like_data, Measure %in% c('negative construction moving ratio', 'positive construction moving ratio') & Child != '0')

individual_emotion_like_data_child <- subset(individual_emotion_like_data, Role == 'Child')
individual_emotion_like_data_parent <- subset(individual_emotion_like_data, Role == 'Parent')

individual_emotion_want_data$Measure <- factor(individual_emotion_want_data$Measure, levels = c('negative construction ratio', 'negative construction moving ratio', 'positive construction ratio', 'positive construction moving ratio'))


individual_emotion_want_data <- subset(individual_emotion_want_data, Measure %in% c('negative construction moving ratio', 'positive construction moving ratio') & Child != '0')

individual_emotion_want_data_child <- subset(individual_emotion_want_data, Role == 'Child')
individual_emotion_want_data_parent <- subset(individual_emotion_want_data, Role == 'Parent')


```{r individualemotionlike, fig.env="figure", fig.pos = "H", fig.align = "center", fig.width=7, fig.height=9, set.cap.width=T, num.cols.cap=1, fig.cap='Individual Variation for  Rejection and its positive counterparts, when the head verb is like',warning=FALSE}

individual_emotion_like_data %>% 
  ggplot(aes(as.numeric(as.character(Age)), round(log(Total_ratio), 2), group = Measure, color = Measure)) +
  geom_line(aes(linetype=Measure), alpha = 1) +
  scale_linetype_manual(values=c("solid", 'solid')) +
  geom_point(aes(color = Measure, shape = Measure), size = 1) +
  scale_shape_manual(values = c(16, 16)) +
  scale_color_manual(values = c("steelblue", "mediumpurple4")) + 
  facet_grid( ~ Child ~ Role) +
  scale_x_continuous(breaks=seq(0, 72, 6)) +
  theme_classic() + 
  theme(text = element_text(size=12, family="Times")) + 
  theme(legend.position="top") +
  xlab("child age (months)") + 
  ylab("log(ratio)") + 
  ylim(-9.5, -2.5) +
  guides(linetype = guide_legend(nrow = 1))

```

```{r individualemotionwant, fig.env="figure", fig.pos = "H", fig.align = "center", fig.width=7, fig.height=9, set.cap.width=T, num.cols.cap=1, fig.cap='Individual Variation for  Rejection and its positive counterparts, when the head verb is want',warning=FALSE}

individual_emotion_want_data %>% 
  ggplot(aes(as.numeric(as.character(Age)), round(log(Total_ratio), 2), group = Measure, color = Measure)) +
  geom_line(aes(linetype=Measure), alpha = 1) +
  scale_linetype_manual(values=c("solid", 'solid')) +
  geom_point(aes(color = Measure, shape = Measure), size = 1) +
  scale_shape_manual(values = c(16, 16)) +
  scale_color_manual(values = c("steelblue", "mediumpurple4")) + 
  facet_grid( ~ Child ~ Role) +
  scale_x_continuous(breaks=seq(0, 72, 6)) +
  theme_classic() + 
  theme(text = element_text(size=12, family="Times")) + 
  theme(legend.position="top") +
  xlab("child age (months)") + 
  ylab("log(ratio)") + 
  ylim(-9.5, -2.5) +
  guides(linetype = guide_legend(nrow = 1))

```


epistemic_know_children = ''

children <- as.vector(unique(subset(epistemic, Age<=36)$Child))

for (i in 1:length(children)){
  select <- data.frame(subset(epistemic, Child == children[i] & Polarity == 'negative' & Role == 'Child' & Head %in% c('know') & grepl(' nan', children[i]) == FALSE))
    if (min(as.vector(unique(select$Age))) < 26 & as.numeric(length(unique(select$Age))) >= 8){
  epistemic_know_children = c(children[i], epistemic_know_children)
  }
}

epistemic_know_children = epistemic_know_children[1: length(epistemic_know_children) - 1]

individual_epistemic_know_data <- 0

epistemic_remember_children = ''

children <- as.vector(unique(subset(epistemic, Age<=36)$Child))

for (i in 1:length(children)){
  select <- data.frame(subset(epistemic, Child == children[i] & Polarity == 'negative' & Role == 'Child' & Head %in% c('remember') & grepl(' nan', children[i]) == FALSE))
    if (min(as.vector(unique(select$Age))) < 26){#} & as.numeric(length(unique(select$Age))) >= 2){
  epistemic_remember_children = c(children[i], epistemic_remember_children)
  }
}

epistemic_remember_children = epistemic_remember_children[1: length(epistemic_remember_children) - 1]

individual_epistemic_remember_data <- 0

epistemic_think_children = ''

children <- as.vector(unique(subset(epistemic, Age<=36)$Child))

for (i in 1:length(children)){
  select <- data.frame(subset(epistemic, Child == children[i] & Polarity == 'negative' & Role == 'Child' & Head %in% c('think') & grepl(' nan', children[i]) == FALSE))
    if (min(as.vector(unique(select$Age))) < 26){#} & as.numeric(length(unique(select$Age))) >= 8){
  epistemic_think_children = c(children[i], epistemic_think_children)
  }
}

epistemic_think_children = epistemic_think_children[1: length(epistemic_think_children) - 1]

individual_epistemic_think_data <- 0

  
for (i in epistemic_know_children){
  
  child_individual_epistemic_neg <- subset(epistemic_neg, Role %in% c('Child') & Child == i)
parent_individual_epistemic_neg <- subset(epistemic_neg, Role %in% c('Parent') & Child == i)

child_individual_epistemic_pos <- subset(epistemic_pos, Role %in% c('Child') & Child == i)
parent_individual_epistemic_pos <- subset(epistemic_pos, Role %in% c('Parent') & Child == i)

child_individual_know_neg <- subset(child_individual_epistemic_neg, Head %in% c('know'))

parent_individual_know_neg <- subset(parent_individual_epistemic_neg, Head %in% c('know'))

child_individual_know_neg <- data.frame(table(child_individual_know_neg$Age))

if (nrow(child_individual_know_neg) != 0){
  
names(child_individual_know_neg) <- c('Age', 'Freq')
child_individual_know_neg$Role <- rep('Child', nrow(child_individual_know_neg))
child_individual_know_neg$Head <- rep('know', nrow(child_individual_know_neg))
temp <- merge(child_individual_know_neg, subset(child_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
child_individual_know_neg <- temp
child_individual_know_neg$Total_ratio <- child_individual_know_neg$Freq / child_individual_know_neg$N_utterance
child_individual_know_neg$Ratio <- child_individual_know_neg$Freq / sum(child_individual_know_neg$Freq)
child_individual_know_neg$Polarity <- rep('negative', nrow(child_individual_know_neg))
child_individual_know_neg$Measure <- rep('negative construction ratio', nrow(child_individual_know_neg))
child_individual_know_neg$Which <- rep('ratio', nrow(child_individual_know_neg))
child_individual_know_neg$Function <- rep('Epistemic', nrow(child_individual_know_neg))
child_individual_know_neg <- negative_moving(child_individual_know_neg, subset(child_individual_descriptive, Child == i))
child_individual_know_neg$Child <- rep(i, nrow(child_individual_know_neg))
individual_epistemic_know_data <- rbind(child_individual_know_neg, individual_epistemic_know_data)

}


parent_individual_know_neg <- data.frame(table(parent_individual_know_neg$Age))

if (nrow(parent_individual_know_neg)){
  
names(parent_individual_know_neg) <- c('Age', 'Freq')
parent_individual_know_neg$Role <- rep('Parent', nrow(parent_individual_know_neg))
parent_individual_know_neg$Head <- rep('know', nrow(parent_individual_know_neg))
temp <- merge(parent_individual_know_neg, subset(parent_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_know_neg <- temp
parent_individual_know_neg$Total_ratio <- parent_individual_know_neg$Freq / parent_individual_know_neg$N_utterance
parent_individual_know_neg$Ratio <- parent_individual_know_neg$Freq / sum(parent_individual_know_neg$Freq)
parent_individual_know_neg$Polarity <- rep('negative', nrow(parent_individual_know_neg))
parent_individual_know_neg$Measure <- rep('negative construction ratio', nrow(parent_individual_know_neg))
parent_individual_know_neg$Which <- rep('ratio', nrow(parent_individual_know_neg))
parent_individual_know_neg$Function <- rep('Epistemic', nrow(parent_individual_know_neg))
parent_individual_know_neg <- negative_moving(parent_individual_know_neg, subset(parent_individual_descriptive, Child == i))
parent_individual_know_neg$Child <- rep(i, nrow(parent_individual_know_neg))
individual_epistemic_know_data <- rbind(parent_individual_know_neg, individual_epistemic_know_data)

}

child_individual_know_pos <- subset(child_individual_epistemic_pos, Head %in% c('know'))

parent_individual_know_pos <- subset(parent_individual_epistemic_pos, Head %in% c('know'))


child_individual_know_pos <- data.frame(table(child_individual_know_pos$Age))

if (nrow(child_individual_know_pos) != 0){
  
names(child_individual_know_pos) <- c('Age', 'Freq')
child_individual_know_pos$Role <- rep('Child', nrow(child_individual_know_pos))
child_individual_know_pos$Head <- rep('know', nrow(child_individual_know_pos))
temp <- merge(child_individual_know_pos, subset(child_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
child_individual_know_pos <- temp
child_individual_know_pos$Total_ratio <- child_individual_know_pos$Freq / child_individual_know_pos$N_utterance
child_individual_know_pos$Ratio <- child_individual_know_pos$Freq / sum(child_individual_know_pos$Freq)
child_individual_know_pos$Polarity <- rep('positive', nrow(child_individual_know_pos))
child_individual_know_pos$Measure <- rep('positive construction ratio', nrow(child_individual_know_pos))
child_individual_know_pos$Which <- rep('ratio', nrow(child_individual_know_pos))
child_individual_know_pos$Function <- rep('Epistemic', nrow(child_individual_know_pos))
child_individual_know_pos <- positive_moving(child_individual_know_pos, subset(child_individual_descriptive, Child == i))
child_individual_know_pos$Child <- rep(i, nrow(child_individual_know_pos))
individual_epistemic_know_data <- rbind(child_individual_know_pos, individual_epistemic_know_data)

}


parent_individual_know_pos <- data.frame(table(parent_individual_know_pos$Age))

if (nrow(parent_individual_know_pos)){
  
names(parent_individual_know_pos) <- c('Age', 'Freq')
parent_individual_know_pos$Role <- rep('Parent', nrow(parent_individual_know_pos))
parent_individual_know_pos$Head <- rep('know', nrow(parent_individual_know_pos))
temp <- merge(parent_individual_know_pos, subset(parent_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_know_pos <- temp
parent_individual_know_pos$Total_ratio <- parent_individual_know_pos$Freq / parent_individual_know_pos$N_utterance
parent_individual_know_pos$Ratio <- parent_individual_know_pos$Freq / sum(parent_individual_know_pos$Freq)
parent_individual_know_pos$Polarity <- rep('positive', nrow(parent_individual_know_pos))
parent_individual_know_pos$Measure <- rep('positive construction ratio', nrow(parent_individual_know_pos))
parent_individual_know_pos$Which <- rep('ratio', nrow(parent_individual_know_pos))
parent_individual_know_pos$Function <- rep('Epistemic', nrow(parent_individual_know_pos))
parent_individual_know_pos <- positive_moving(parent_individual_know_pos, subset(parent_individual_descriptive, Child == i))
parent_individual_know_pos$Child <- rep(i, nrow(parent_individual_know_pos))
individual_epistemic_know_data <- rbind(parent_individual_know_pos, individual_epistemic_know_data)

}}


for (i in epistemic_remember_children){
  
  child_individual_epistemic_neg <- subset(epistemic_neg, Role %in% c('Child') & Child == i)
parent_individual_epistemic_neg <- subset(epistemic_neg, Role %in% c('Parent') & Child == i)

child_individual_epistemic_pos <- subset(epistemic_pos, Role %in% c('Child') & Child == i)
parent_individual_epistemic_pos <- subset(epistemic_pos, Role %in% c('Parent') & Child == i)

child_individual_remember_neg <- subset(child_individual_epistemic_neg, Head %in% c('remember'))

parent_individual_remember_neg <- subset(parent_individual_epistemic_neg, Head %in% c('remember'))


child_individual_remember_neg <- data.frame(table(child_individual_remember_neg$Age))

if (nrow(child_individual_remember_neg) != 0){
  
names(child_individual_remember_neg) <- c('Age', 'Freq')
child_individual_remember_neg$Role <- rep('Child', nrow(child_individual_remember_neg))
child_individual_remember_neg$Head <- rep('remember', nrow(child_individual_remember_neg))
temp <- merge(child_individual_remember_neg, subset(child_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
child_individual_remember_neg <- temp
child_individual_remember_neg$Total_ratio <- child_individual_remember_neg$Freq / child_individual_remember_neg$N_utterance
child_individual_remember_neg$Ratio <- child_individual_remember_neg$Freq / sum(child_individual_remember_neg$Freq)
child_individual_remember_neg$Polarity <- rep('negative', nrow(child_individual_remember_neg))
child_individual_remember_neg$Measure <- rep('negative construction ratio', nrow(child_individual_remember_neg))
child_individual_remember_neg$Which <- rep('ratio', nrow(child_individual_remember_neg))
child_individual_remember_neg$Function <- rep('Epistemic', nrow(child_individual_remember_neg))
child_individual_remember_neg <- negative_moving(child_individual_remember_neg, subset(child_individual_descriptive, Child == i))
child_individual_remember_neg$Child <- rep(i, nrow(child_individual_remember_neg))
individual_epistemic_remember_data <- rbind(child_individual_remember_neg, individual_epistemic_remember_data)

}


parent_individual_remember_neg <- data.frame(table(parent_individual_remember_neg$Age))

if (nrow(parent_individual_remember_neg) != 0){
  
names(parent_individual_remember_neg) <- c('Age', 'Freq')
parent_individual_remember_neg$Role <- rep('Parent', nrow(parent_individual_remember_neg))
parent_individual_remember_neg$Head <- rep('remember', nrow(parent_individual_remember_neg))
temp <- merge(parent_individual_remember_neg, subset(parent_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_remember_neg <- temp
parent_individual_remember_neg$Total_ratio <- parent_individual_remember_neg$Freq / parent_individual_remember_neg$N_utterance
parent_individual_remember_neg$Ratio <- parent_individual_remember_neg$Freq / sum(parent_individual_remember_neg$Freq)
parent_individual_remember_neg$Polarity <- rep('negative', nrow(parent_individual_remember_neg))
parent_individual_remember_neg$Measure <- rep('negative construction ratio', nrow(parent_individual_remember_neg))
parent_individual_remember_neg$Which <- rep('ratio', nrow(parent_individual_remember_neg))
parent_individual_remember_neg$Function <- rep('Epistemic', nrow(parent_individual_remember_neg))
parent_individual_remember_neg <- negative_moving(parent_individual_remember_neg, subset(parent_individual_descriptive, Child == i))
parent_individual_remember_neg$Child <- rep(i, nrow(parent_individual_remember_neg))
individual_epistemic_remember_data <- rbind(parent_individual_remember_neg, individual_epistemic_remember_data)

}


child_individual_remember_pos <- subset(child_individual_epistemic_pos, Head %in% c('remember'))

parent_individual_remember_pos <- subset(parent_individual_epistemic_pos, Head %in% c('remember'))

child_individual_remember_pos <- data.frame(table(child_individual_remember_pos$Age))

if (nrow(child_individual_remember_pos) != 0){
  
names(child_individual_remember_pos) <- c('Age', 'Freq')
child_individual_remember_pos$Role <- rep('Child', nrow(child_individual_remember_pos))
child_individual_remember_pos$Head <- rep('remember', nrow(child_individual_remember_pos))
temp <- merge(child_individual_remember_pos, subset(child_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
child_individual_remember_pos <- temp
child_individual_remember_pos$Total_ratio <- child_individual_remember_pos$Freq / child_individual_remember_pos$N_utterance
child_individual_remember_pos$Ratio <- child_individual_remember_pos$Freq / sum(child_individual_remember_pos$Freq)
child_individual_remember_pos$Polarity <- rep('positive', nrow(child_individual_remember_pos))
child_individual_remember_pos$Measure <- rep('positive construction ratio', nrow(child_individual_remember_pos))
child_individual_remember_pos$Which <- rep('ratio', nrow(child_individual_remember_pos))
child_individual_remember_pos$Function <- rep('Epistemic', nrow(child_individual_remember_pos))
child_individual_remember_pos <- positive_moving(child_individual_remember_pos, subset(child_individual_descriptive, Child == i))
child_individual_remember_pos$Child <- rep(i, nrow(child_individual_remember_pos))
individual_epistemic_remember_data <- rbind(child_individual_remember_pos, individual_epistemic_remember_data)

}


parent_individual_remember_pos <- data.frame(table(parent_individual_remember_pos$Age))

if (nrow(parent_individual_remember_pos) != 0){
  
names(parent_individual_remember_pos) <- c('Age', 'Freq')
parent_individual_remember_pos$Role <- rep('Parent', nrow(parent_individual_remember_pos))
parent_individual_remember_pos$Head <- rep('remember', nrow(parent_individual_remember_pos))
temp <- merge(parent_individual_remember_pos, subset(parent_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_remember_pos <- temp
parent_individual_remember_pos$Total_ratio <- parent_individual_remember_pos$Freq / parent_individual_remember_pos$N_utterance
parent_individual_remember_pos$Ratio <- parent_individual_remember_pos$Freq / sum(parent_individual_remember_pos$Freq)
parent_individual_remember_pos$Polarity <- rep('positive', nrow(parent_individual_remember_pos))
parent_individual_remember_pos$Measure <- rep('positive construction ratio', nrow(parent_individual_remember_pos))
parent_individual_remember_pos$Which <- rep('ratio', nrow(parent_individual_remember_pos))
parent_individual_remember_pos$Function <- rep('Epistemic', nrow(parent_individual_remember_pos))
parent_individual_remember_pos <- positive_moving(parent_individual_remember_pos, subset(parent_individual_descriptive, Child == i))
parent_individual_remember_pos$Child <- rep(i, nrow(parent_individual_remember_pos))
individual_epistemic_remember_data <- rbind(parent_individual_remember_pos, individual_epistemic_remember_data)


}}

for (i in epistemic_think_children){
  
child_individual_epistemic_neg <- subset(epistemic_neg, Role %in% c('Child') & Child == i)
parent_individual_epistemic_neg <- subset(epistemic_neg, Role %in% c('Parent') & Child == i)

child_individual_epistemic_pos <- subset(epistemic_pos, Role %in% c('Child') & Child == i)
parent_individual_epistemic_pos <- subset(epistemic_pos, Role %in% c('Parent') & Child == i)

child_individual_think_neg <- subset(child_individual_epistemic_neg, Head %in% c('think'))

parent_individual_think_neg <- subset(parent_individual_epistemic_neg, Head %in% c('think'))


child_individual_think_neg <- data.frame(table(child_individual_think_neg$Age))

if (nrow(child_individual_think_neg) != 0){
  
names(child_individual_think_neg) <- c('Age', 'Freq')
child_individual_think_neg$Role <- rep('Child', nrow(child_individual_think_neg))
child_individual_think_neg$Head <- rep('think', nrow(child_individual_think_neg))
temp <- merge(child_individual_think_neg, subset(child_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
child_individual_think_neg <- temp
child_individual_think_neg$Total_ratio <- child_individual_think_neg$Freq / child_individual_think_neg$N_utterance
child_individual_think_neg$Ratio <- child_individual_think_neg$Freq / sum(child_individual_think_neg$Freq)
child_individual_think_neg$Polarity <- rep('negative', nrow(child_individual_think_neg))
child_individual_think_neg$Measure <- rep('negative construction ratio', nrow(child_individual_think_neg))
child_individual_think_neg$Which <- rep('ratio', nrow(child_individual_think_neg))
child_individual_think_neg$Function <- rep('Epistemic', nrow(child_individual_think_neg))
child_individual_think_neg <- negative_moving(child_individual_think_neg, subset(child_individual_descriptive, Child == i))
child_individual_think_neg$Child <- rep(i, nrow(child_individual_think_neg))
individual_epistemic_think_data <- rbind(child_individual_think_neg, individual_epistemic_think_data)

}


parent_individual_think_neg <- data.frame(table(parent_individual_think_neg$Age))

if (nrow(parent_individual_think_neg) != 0){
  
names(parent_individual_think_neg) <- c('Age', 'Freq')
parent_individual_think_neg$Role <- rep('Parent', nrow(parent_individual_think_neg))
parent_individual_think_neg$Head <- rep('think', nrow(parent_individual_think_neg))
temp <- merge(parent_individual_think_neg, subset(parent_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_think_neg <- temp
parent_individual_think_neg$Total_ratio <- parent_individual_think_neg$Freq / parent_individual_think_neg$N_utterance
parent_individual_think_neg$Ratio <- parent_individual_think_neg$Freq / sum(parent_individual_think_neg$Freq)
parent_individual_think_neg$Polarity <- rep('negative', nrow(parent_individual_think_neg))
parent_individual_think_neg$Measure <- rep('negative construction ratio', nrow(parent_individual_think_neg))
parent_individual_think_neg$Which <- rep('ratio', nrow(parent_individual_think_neg))
parent_individual_think_neg$Function <- rep('Epistemic', nrow(parent_individual_think_neg))
parent_individual_think_neg <- negative_moving(parent_individual_think_neg, subset(parent_individual_descriptive, Child == i))
parent_individual_think_neg$Child <- rep(i, nrow(parent_individual_think_neg))
individual_epistemic_think_data <- rbind(parent_individual_think_neg, individual_epistemic_think_data)

}


child_individual_think_pos <- subset(child_individual_epistemic_pos, Head %in% c('think'))

parent_individual_think_pos <- subset(parent_individual_epistemic_pos, Head %in% c('think'))


child_individual_think_pos <- data.frame(table(child_individual_think_pos$Age))

if (nrow(child_individual_think_pos)){
  
names(child_individual_think_pos) <- c('Age', 'Freq')
child_individual_think_pos$Role <- rep('Child', nrow(child_individual_think_pos))
child_individual_think_pos$Head <- rep('think', nrow(child_individual_think_pos))
temp <- merge(child_individual_think_pos, subset(child_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
child_individual_think_pos <- temp
child_individual_think_pos$Total_ratio <- child_individual_think_pos$Freq / child_individual_think_pos$N_utterance
child_individual_think_pos$Ratio <- child_individual_think_pos$Freq / sum(child_individual_think_pos$Freq)
child_individual_think_pos$Polarity <- rep('positive', nrow(child_individual_think_pos))
child_individual_think_pos$Measure <- rep('positive construction ratio', nrow(child_individual_think_pos))
child_individual_think_pos$Which <- rep('ratio', nrow(child_individual_think_pos))
child_individual_think_pos$Function <- rep('Epistemic', nrow(child_individual_think_pos))
child_individual_think_pos <- positive_moving(child_individual_think_pos, subset(child_individual_descriptive, Child == i))
child_individual_think_pos$Child <- rep(i, nrow(child_individual_think_pos))
individual_epistemic_think_data <- rbind(child_individual_think_pos, individual_epistemic_think_data)

}

parent_individual_think_pos <- data.frame(table(parent_individual_think_pos$Age))

if (nrow(parent_individual_think_pos) != 0){
  
names(parent_individual_think_pos) <- c('Age', 'Freq')
parent_individual_think_pos$Role <- rep('Parent', nrow(parent_individual_think_pos))
parent_individual_think_pos$Head <- rep('think', nrow(parent_individual_think_pos))
temp <- merge(parent_individual_think_pos, subset(parent_individual_descriptive, Child == i)[,-c(4)], by.x = 'Age', all.x = TRUE)
parent_individual_think_pos <- temp
parent_individual_think_pos$Total_ratio <- parent_individual_think_pos$Freq / parent_individual_think_pos$N_utterance
parent_individual_think_pos$Ratio <- parent_individual_think_pos$Freq / sum(parent_individual_think_pos$Freq)
parent_individual_think_pos$Polarity <- rep('positive', nrow(parent_individual_think_pos))
parent_individual_think_pos$Measure <- rep('positive construction ratio', nrow(parent_individual_think_pos))
parent_individual_think_pos$Which <- rep('ratio', nrow(parent_individual_think_pos))
parent_individual_think_pos$Function <- rep('Epistemic', nrow(parent_individual_think_pos))
parent_individual_think_pos <- positive_moving(parent_individual_think_pos, subset(parent_individual_descriptive, Child == i))
parent_individual_think_pos$Child <- rep(i, nrow(parent_individual_think_pos))
individual_epistemic_think_data <- rbind(parent_individual_think_pos, individual_epistemic_think_data)

}}


individual_epistemic_know_data$Measure <- factor(individual_epistemic_know_data$Measure, levels = c('negative construction ratio', 'negative construction moving ratio', 'positive construction ratio', 'positive construction moving ratio'))

individual_epistemic_know_data <- subset(individual_epistemic_know_data, Measure %in% c('negative construction moving ratio', 'positive construction moving ratio') & Child != '0')

individual_epistemic_know_data_child <- subset(individual_epistemic_know_data, Role == 'Child')
individual_epistemic_know_data_parent <- subset(individual_epistemic_know_data, Role == 'Parent')

individual_epistemic_remember_data$Measure <- factor(individual_epistemic_remember_data$Measure, levels = c('negative construction ratio', 'negative construction moving ratio', 'positive construction ratio', 'positive construction moving ratio'))

individual_epistemic_remember_data <- subset(individual_epistemic_remember_data, Measure %in% c('negative construction moving ratio', 'positive construction moving ratio') & Child != '0')

individual_epistemic_remember_data_child <- subset(individual_epistemic_remember_data, Role == 'Child')
individual_epistemic_remember_data_parent <- subset(individual_epistemic_remember_data, Role == 'Parent')


individual_epistemic_think_data$Measure <- factor(individual_epistemic_think_data$Measure, levels = c('negative construction ratio', 'negative construction moving ratio', 'positive construction ratio', 'positive construction moving ratio'))

individual_epistemic_think_data <- subset(individual_epistemic_think_data, Measure %in% c('negative construction moving ratio', 'positive construction moving ratio') & Child != '0')

individual_epistemic_think_data_child <- subset(individual_epistemic_think_data, Role == 'Child')
individual_epistemic_think_data_parent <- subset(individual_epistemic_think_data, Role == 'Parent')


```{r individualepistemicknow, fig.env="figure", fig.pos = "H", fig.align = "center", fig.width=7, fig.height=9, set.cap.width=T, num.cols.cap=1, fig.cap='Individual variation for Epistemic negation and its positive counterparts, when the head verb is know', warning=FALSE}


individual_epistemic_know_data %>% 
  ggplot(aes(as.numeric(as.character(Age)), round(log(Total_ratio), 2), group = Measure, color = Measure)) +
  geom_line(aes(linetype=Measure), alpha = 1) +
  scale_linetype_manual(values=c('solid', 'solid')) +
  geom_point(aes(color = Measure, shape = Measure), size = 1) +
  scale_shape_manual(values = c(16, 16)) +
  scale_color_manual(values = c("steelblue", "mediumpurple4")) +
  facet_grid(  ~ Child ~ Role) +
  scale_x_continuous(breaks=seq(0, 72, 6)) +
  theme_classic() + 
  theme(text = element_text(size=12, family="Times")) + 
  theme(legend.position="top") +
  xlab("child age (months)") + 
  ylab("log(ratio)") + 
  guides(linetype = guide_legend(nrow = 2))

```

```{r individualepistemicremember, fig.env="figure", fig.pos = "H", fig.align = "center", fig.width=7, fig.height=9, set.cap.width=T, num.cols.cap=1, fig.cap='Individual variation for Epistemic negation and its positive counterparts, when the head verb is remember', warning=FALSE}


individual_epistemic_remember_data%>% 
  ggplot(aes(as.numeric(as.character(Age)), round(log(Total_ratio), 2), group = Measure, color = Measure)) +
  geom_line(aes(linetype=Measure), alpha = 1) +
  scale_linetype_manual(values=c('solid', 'solid')) +
  geom_point(aes(color = Measure, shape = Measure), size = 1) +
  scale_shape_manual(values = c(16, 16)) +
  scale_color_manual(values = c("steelblue", "mediumpurple4")) +
  facet_grid(  ~ Child ~ Role) +
  scale_x_continuous(breaks=seq(0, 72, 6)) +
  theme_classic() + 
  theme(text = element_text(size=12, family="Times")) + 
  theme(legend.position="top") +
  xlab("child age (months)") + 
  ylab("log(ratio)") + 
  guides(linetype = guide_legend(nrow = 2))

```

```{r individualepistemicthink, fig.env="figure", fig.pos = "H", fig.align = "center", fig.width=7, fig.height=9, set.cap.width=T, num.cols.cap=1, fig.cap='Individual variation for Epistemic negation and its positive counterparts, when the head verb is think', warning=FALSE}


individual_epistemic_think_data %>% 
  ggplot(aes(as.numeric(as.character(Age)), round(log(Total_ratio), 2), group = Measure, color = Measure)) +
  geom_line(aes(linetype=Measure), alpha = 1) +
  scale_linetype_manual(values=c('solid', 'solid')) +
  geom_point(aes(color = Measure, shape = Measure), size = 1) +
  scale_shape_manual(values = c(16, 16)) +
  scale_color_manual(values = c("steelblue", "mediumpurple4")) +
  facet_grid(  ~ Child ~ Role) +
  scale_x_continuous(breaks=seq(0, 72, 6)) +
  theme_classic() + 
  theme(text = element_text(size=12, family="Times")) + 
  theme(legend.position="top") +
  xlab("child age (months)") + 
  ylab("log(ratio)") + 
  guides(linetype = guide_legend(nrow = 2))

```

-->